#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_MACH_MT6757) += 2.0/
obj-$(CONFIG_MACH_KIBOPLUS) += 2.0/
obj-$(CONFIG_MACH_MT6799) += 3.0/
obj-$(CONFIG_MACH_MT6759) += 2.2/
obj-$(CONFIG_MACH_MT6763) += 2.0/
obj-$(CONFIG_MACH_MT6758) += 2.0/
obj-$(CONFIG_MACH_MT6739) += 2.0/

