# Core
obj-$(CONFIG_PINCTRL_MTK_COMMON)	+= pinctrl-mtk-common.o
# obj-y	+= pinctrl-mtk-common.o
# SoC Drivers
obj-$(CONFIG_PINCTRL_MT8135)		+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8173)		+= pinctrl-mt8173.o
obj-$(CONFIG_PINCTRL_MT6735)		+= pinctrl-mt6735.o

