# Core
obj-$(CONFIG_PINCTRL_MTK_COMMON)	+= pinctrl-mtk-common.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT8135)		+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8127)		+= pinctrl-mt8127.o
obj-$(CONFIG_PINCTRL_MT8167)		+= pinctrl-mt8167.o
obj-$(CONFIG_PINCTRL_MT8173)		+= pinctrl-mt8173.o
obj-$(CONFIG_PINCTRL_MT6392)		+= pinctrl-mt6392.o
obj-$(CONFIG_PINCTRL_MT6397)		+= pinctrl-mt6397.o
obj-$(CONFIG_PINCTRL_MT6757)		+= pinctrl-mt6757.o
obj-$(CONFIG_PINCTRL_MT6759)		+= pinctrl-mt6759.o
obj-$(CONFIG_PINCTRL_MT6763)		+= pinctrl-mt6763.o
obj-$(CONFIG_PINCTRL_MT6799)		+= pinctrl-mt6799.o
