ccflags-y += -I$(srctree)/drivers/misc/mediatek/power_gs/$(MTK_PLATFORM)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/

obj-y += mt_power_gs_6351_array.o
obj-y += mt_power_gs_misc.o
