extern const unsigned int *MT6351_PMIC_REG_gs_flightmode_suspend_mode;
extern unsigned int MT6351_PMIC_REG_gs_flightmode_suspend_mode_len;

extern const unsigned int *MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode;
extern unsigned int MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode_len;
