/* This file is generated by GenLP_setting.pl v1.5.7 */

#include <linux/init.h>
#include <linux/module.h>
#include <linux/kernel.h>

#include <mt-plat/mt_typedefs.h>
#include <mach/mt_power_gs.h>
const unsigned int MT6351_PMIC_REG_gs_video_record_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_video_record = MT6351_PMIC_REG_gs_video_record_data;
unsigned int MT6351_PMIC_REG_gs_video_record_len = 3;
const unsigned int MT6351_PMIC_REG_gs_early_suspend_deep_idle_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_early_suspend_deep_idle = MT6351_PMIC_REG_gs_early_suspend_deep_idle_data;
unsigned int MT6351_PMIC_REG_gs_early_suspend_deep_idle_len = 3;
const unsigned int MT6351_PMIC_REG_gs_datalink_3g_and_4g_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_datalink_3g_and_4g = MT6351_PMIC_REG_gs_datalink_3g_and_4g_data;
unsigned int MT6351_PMIC_REG_gs_datalink_3g_and_4g_len = 3;
const unsigned int MT6351_PMIC_REG_gs_talking_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_talking = MT6351_PMIC_REG_gs_talking_data;
unsigned int MT6351_PMIC_REG_gs_talking_len = 3;
const unsigned int MT6351_PMIC_REG_gs_video_play_and_3d_gaming_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_video_play_and_3d_gaming = MT6351_PMIC_REG_gs_video_play_and_3d_gaming_data;
unsigned int MT6351_PMIC_REG_gs_video_play_and_3d_gaming_len = 3;
const unsigned int MT6351_PMIC_REG_gs_flightmode_suspend_mode_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x0000, 0xFFFF, 0xFEFC,	/* TOP_CKPDN_CON0 */
	0x0000, 0x8000, 0x0000,	/* FQMTR_CON0 */
	0x0000, 0x0001, 0x0000,	/* BUCK_VCORE_CON0 */
	0x0000, 0x00EE, 0x0006,	/* LDO_VA18_CON0 */
	0x0000, 0x0001, 0x0000,	/* FGADC_CON0 */
	0x0002, 0x0038, 0x0000,	/* BUCK_VCORE_CON1 */
	0x0002, 0x0001, 0x0000,	/* ACCDET_CON1 */
	0x0004, 0x0270, 0x0070,	/* TOP_CON */
	0x0004, 0x0001, 0x0001,	/* BUCK_VCORE_CON2 */
	0x0004, 0x380C, 0x0008,	/* LDO_VTCXO24_CON0 */
	0x0006, 0x1FFF, 0x00AC,	/* TOP_CKPDN_CON1 */
	0x0008, 0x380C, 0x0808,	/* LDO_VTCXO28_CON0 */
	0x000C, 0xFEFC, 0x7470,	/* TOP_CKPDN_CON2 */
	0x000C, 0x000E, 0x0000,	/* LDO_VCN28_CON0 */
	0x0012, 0x0FFF, 0x0DE4,	/* TOP_CKPDN_CON3 */
	0x0012, 0x0100, 0x0100,	/* BUCK_VCORE_CON9 */
	0x0012, 0x000A, 0x0000,	/* LDO_VCAMA_CON0 */
	0x0012, 0x1000, 0x1000,	/* AUDDEC_ANA_CON9 */
	0x0014, 0x0001, 0x0000,	/* BUCK_VGPU_CON0 */
	0x0016, 0x0080, 0x0000,	/* STRUP_CON11 */
	0x0016, 0x00EE, 0x0006,	/* LDO_VUSB33_CON0 */
	0x0018, 0x006F, 0x0000,	/* TOP_CKPDN_CON4 */
	0x0018, 0x0001, 0x0000,	/* BUCK_VGPU_CON2 */
	0x001C, 0x000E, 0x0000,	/* LDO_VSIM1_CON0 */
	0x001E, 0x7FDF, 0x3FC0,	/* TOP_CKPDN_CON5 */
	0x0022, 0x000E, 0x0000,	/* LDO_VSIM2_CON0 */
	0x0024, 0xF400, 0x0000,	/* TOP_CKSEL_CON0 */
	0x0024, 0xFFFF, 0x0024,	/* FGADC_CON18 */
	0x0026, 0x0100, 0x0000,	/* BUCK_VGPU_CON9 */
	0x0028, 0x0001, 0x0000,	/* BUCK_VMODEM_CON0 */
	0x0028, 0x000E, 0x0000,	/* LDO_VEMC_CON0 */
	0x002A, 0x000F, 0x0000,	/* ISINK_EN_CTRL */
	0x002C, 0x0001, 0x0000,	/* BUCK_VMODEM_CON2 */
	0x002E, 0x000E, 0x0000,	/* LDO_VMCH_CON0 */
	0x0034, 0x00EE, 0x0006,	/* LDO_VIO28_CON0 */
	0x003A, 0x0100, 0x0000,	/* BUCK_VMODEM_CON9 */
	0x003A, 0x000E, 0x0000,	/* LDO_VIBR_CON0 */
	0x003C, 0x0001, 0x0000,	/* BUCK_VMD1_CON0 */
	0x003C, 0x000F, 0x0000,	/* ISINK_EN_CTRL_SMPL */
	0x0040, 0x0001, 0x0000,	/* BUCK_VMD1_CON2 */
	0x0040, 0x0006, 0x0000,	/* LDO_VCAMD_CON0 */
	0x0046, 0x0010, 0x0000,	/* CHRIND_EN_CTRL */
	0x0046, 0x380C, 0x0808,	/* LDO_VRF18_CON0 */
	0x0048, 0x0CFF, 0x00F7,	/* TOP_CKHWEN_CON0 */
	0x004C, 0x00EE, 0x0006,	/* LDO_VIO18_CON0 */
	0x004E, 0x0037, 0x0037,	/* TOP_CKHWEN_CON1 */
	0x004E, 0x0100, 0x0000,	/* BUCK_VMD1_CON9 */
	0x0050, 0x0001, 0x0000,	/* BUCK_VSRAM_MD_CON0 */
	0x0052, 0x000E, 0x0000,	/* LDO_VCN18_CON0 */
	0x0054, 0x002F, 0x002F,	/* TOP_CKHWEN_CON2 */
	0x0054, 0x0001, 0x0000,	/* BUCK_VSRAM_MD_CON2 */
	0x0058, 0x0006, 0x0000,	/* LDO_VCAMIO_CON0 */
	0x005E, 0x000E, 0x0000,	/* LDO_VSRAM_PROC_CON0 */
	0x0060, 0x0F3F, 0x0100,	/* TOP_CLKSQ */
	0x0062, 0x0100, 0x0000,	/* BUCK_VSRAM_MD_CON9 */
	0x0064, 0x0001, 0x0000,	/* BUCK_VS1_CON0 */
	0x0064, 0x000E, 0x0000,	/* LDO_VXO22_CON0 */
	0x0066, 0x0002, 0x0002,	/* TOP_CLKSQ_RTC */
	0x0066, 0x0038, 0x0000,	/* BUCK_VS1_CON1 */
	0x0068, 0x0001, 0x0001,	/* BUCK_VS1_CON2 */
	0x0068, 0x380C, 0x0808,	/* LDO_VRF12_CON0 */
	0x006E, 0x00EE, 0x0006,	/* LDO_VA10_CON0 */
	0x0074, 0x00EE, 0x0006,	/* LDO_VDRAM_CON0 */
	0x0076, 0x0100, 0x0100,	/* BUCK_VS1_CON9 */
	0x0078, 0x0001, 0x0000,	/* BUCK_VS2_CON0 */
	0x007A, 0x0038, 0x0000,	/* BUCK_VS2_CON1 */
	0x007A, 0x000A, 0x0000,	/* LDO_VMIPI_CON0 */
	0x007C, 0x0001, 0x0001,	/* BUCK_VS2_CON2 */
	0x0080, 0x000E, 0x0000,	/* LDO_VGP3_CON0 */
	0x0086, 0x000E, 0x0000,	/* LDO_VBIF28_CON0 */
	0x008A, 0x0100, 0x0100,	/* BUCK_VS2_CON9 */
	0x008C, 0x0001, 0x0000,	/* BUCK_VPA_CON0 */
	0x008C, 0x0006, 0x0000,	/* LDO_VEFUSE_CON0 */
	0x0090, 0x0001, 0x0000,	/* BUCK_VPA_CON2 */
	0x0092, 0x0004, 0x0000,	/* LDO_VCN33_CON0 */
	0x0098, 0x000A, 0x0000,	/* LDO_VCN33_CON3 */
	0x009A, 0x000A, 0x0000,	/* LDO_VCN33_CON4 */
	0x009C, 0x00EC, 0x0004,	/* LDO_VLDO28_CON0 */
	0x009E, 0x0100, 0x0000,	/* BUCK_VPA_CON9 */
	0x00A2, 0x0002, 0x0002,	/* LDO_VLDO28_CON3 */
	0x00A4, 0x0002, 0x0002,	/* LDO_VLDO28_CON4 */
	0x00AA, 0x000E, 0x0000,	/* LDO_VMC_CON0 */
	0x00B2, 0x0100, 0x0000	/* BUCK_VSRAM_PROC_CON9 */
};

const unsigned int *MT6351_PMIC_REG_gs_flightmode_suspend_mode = MT6351_PMIC_REG_gs_flightmode_suspend_mode_data;
unsigned int MT6351_PMIC_REG_gs_flightmode_suspend_mode_len = 249;

const unsigned int MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x0000, 0xFFFF, 0xFEFC,	/* TOP_CKPDN_CON0 */
	0x0000, 0x8000, 0x0000,	/* FQMTR_CON0 */
	0x0000, 0x0001, 0x0000,	/* BUCK_VCORE_CON0 */
	0x0000, 0x00EE, 0x0006,	/* LDO_VA18_CON0 */
	0x0000, 0x0001, 0x0000,	/* FGADC_CON0 */
	0x0002, 0x0038, 0x0000,	/* BUCK_VCORE_CON1 */
	0x0002, 0x0001, 0x0000,	/* ACCDET_CON1 */
	0x0004, 0x0270, 0x0070,	/* TOP_CON */
	0x0004, 0x0001, 0x0001,	/* BUCK_VCORE_CON2 */
	0x0004, 0x380C, 0x0008,	/* LDO_VTCXO24_CON0 */
	0x0006, 0x1FFF, 0x00AC,	/* TOP_CKPDN_CON1 */
	0x0008, 0x380C, 0x0808,	/* LDO_VTCXO28_CON0 */
	0x000C, 0xFEFC, 0x7470,	/* TOP_CKPDN_CON2 */
	0x000C, 0x000E, 0x0000,	/* LDO_VCN28_CON0 */
	0x0012, 0x0FFF, 0x0DE4,	/* TOP_CKPDN_CON3 */
	0x0012, 0x0100, 0x0100,	/* BUCK_VCORE_CON9 */
	0x0012, 0x000A, 0x0000,	/* LDO_VCAMA_CON0 */
	0x0012, 0x1000, 0x1000,	/* AUDDEC_ANA_CON9 */
	0x0014, 0x0001, 0x0000,	/* BUCK_VGPU_CON0 */
	0x0016, 0x0080, 0x0000,	/* STRUP_CON11 */
	0x0016, 0x00EE, 0x0006,	/* LDO_VUSB33_CON0 */
	0x0018, 0x006F, 0x0000,	/* TOP_CKPDN_CON4 */
	0x0018, 0x0001, 0x0000,	/* BUCK_VGPU_CON2 */
	0x001C, 0x000E, 0x0000,	/* LDO_VSIM1_CON0 */
	0x001E, 0x7FDF, 0x3FC0,	/* TOP_CKPDN_CON5 */
	0x0022, 0x000E, 0x0000,	/* LDO_VSIM2_CON0 */
	0x0024, 0xF400, 0x0000,	/* TOP_CKSEL_CON0 */
	0x0024, 0xFFFF, 0x0024,	/* FGADC_CON18 */
	0x0026, 0x0100, 0x0000,	/* BUCK_VGPU_CON9 */
	0x0028, 0x0001, 0x0000,	/* BUCK_VMODEM_CON0 */
	0x0028, 0x000E, 0x0000,	/* LDO_VEMC_CON0 */
	0x002A, 0x000F, 0x0000,	/* ISINK_EN_CTRL */
	0x002C, 0x0001, 0x0000,	/* BUCK_VMODEM_CON2 */
	0x002E, 0x000E, 0x0000,	/* LDO_VMCH_CON0 */
	0x0034, 0x00EE, 0x0006,	/* LDO_VIO28_CON0 */
	0x003A, 0x0100, 0x0000,	/* BUCK_VMODEM_CON9 */
	0x003A, 0x000E, 0x0000,	/* LDO_VIBR_CON0 */
	0x003C, 0x0001, 0x0000,	/* BUCK_VMD1_CON0 */
	0x003C, 0x000F, 0x0000,	/* ISINK_EN_CTRL_SMPL */
	0x0040, 0x0001, 0x0000,	/* BUCK_VMD1_CON2 */
	0x0040, 0x0006, 0x0000,	/* LDO_VCAMD_CON0 */
	0x0046, 0x0010, 0x0000,	/* CHRIND_EN_CTRL */
	0x0046, 0x380C, 0x0808,	/* LDO_VRF18_CON0 */
	0x0048, 0x0CFF, 0x00F7,	/* TOP_CKHWEN_CON0 */
	0x004C, 0x00EE, 0x0006,	/* LDO_VIO18_CON0 */
	0x004E, 0x0037, 0x0037,	/* TOP_CKHWEN_CON1 */
	0x004E, 0x0100, 0x0000,	/* BUCK_VMD1_CON9 */
	0x0050, 0x0001, 0x0000,	/* BUCK_VSRAM_MD_CON0 */
	0x0052, 0x000E, 0x0000,	/* LDO_VCN18_CON0 */
	0x0054, 0x002F, 0x002F,	/* TOP_CKHWEN_CON2 */
	0x0054, 0x0001, 0x0001,	/* BUCK_VSRAM_MD_CON2 */
	0x0058, 0x0006, 0x0000,	/* LDO_VCAMIO_CON0 */
	0x005E, 0x000E, 0x0000,	/* LDO_VSRAM_PROC_CON0 */
	0x0060, 0x0F3F, 0x0100,	/* TOP_CLKSQ */
	0x0062, 0x0100, 0x0000,	/* BUCK_VSRAM_MD_CON9 */
	0x0064, 0x0001, 0x0000,	/* BUCK_VS1_CON0 */
	0x0064, 0x000E, 0x0000,	/* LDO_VXO22_CON0 */
	0x0066, 0x0002, 0x0002,	/* TOP_CLKSQ_RTC */
	0x0066, 0x0038, 0x0000,	/* BUCK_VS1_CON1 */
	0x0068, 0x0001, 0x0001,	/* BUCK_VS1_CON2 */
	0x0068, 0x380C, 0x0808,	/* LDO_VRF12_CON0 */
	0x006E, 0x00EE, 0x0006,	/* LDO_VA10_CON0 */
	0x0074, 0x00EE, 0x0006,	/* LDO_VDRAM_CON0 */
	0x0076, 0x0100, 0x0100,	/* BUCK_VS1_CON9 */
	0x0078, 0x0001, 0x0000,	/* BUCK_VS2_CON0 */
	0x007A, 0x0038, 0x0000,	/* BUCK_VS2_CON1 */
	0x007A, 0x380E, 0x0808,	/* LDO_VMIPI_CON0 */
	0x007C, 0x0001, 0x0001,	/* BUCK_VS2_CON2 */
	0x0080, 0x000E, 0x0000,	/* LDO_VGP3_CON0 */
	0x0086, 0x000E, 0x0000,	/* LDO_VBIF28_CON0 */
	0x008A, 0x0100, 0x0100,	/* BUCK_VS2_CON9 */
	0x008C, 0x0001, 0x0000,	/* BUCK_VPA_CON0 */
	0x008C, 0x0006, 0x0000,	/* LDO_VEFUSE_CON0 */
	0x0090, 0x0001, 0x0001,	/* BUCK_VPA_CON2 */
	0x0092, 0x0004, 0x0000,	/* LDO_VCN33_CON0 */
	0x0098, 0x000A, 0x0000,	/* LDO_VCN33_CON3 */
	0x009A, 0x000A, 0x0000,	/* LDO_VCN33_CON4 */
	0x009C, 0x00EC, 0x0004,	/* LDO_VLDO28_CON0 */
	0x009E, 0x0100, 0x0000,	/* BUCK_VPA_CON9 */
	0x00A2, 0x0002, 0x0002,	/* LDO_VLDO28_CON3 */
	0x00A4, 0x0002, 0x0002,	/* LDO_VLDO28_CON4 */
	0x00AA, 0x000E, 0x0000,	/* LDO_VMC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode =
MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode_data;
unsigned int MT6351_PMIC_REG_gs_early_suspend_deep_idle__mode_len = 246;
const unsigned int MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_32k_removal_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_32k_removal =
MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_32k_removal_data;
unsigned int MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_32k_removal_len = 3;
const unsigned int MT6351_PMIC_REG_gs_paging_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_paging = MT6351_PMIC_REG_gs_paging_data;
unsigned int MT6351_PMIC_REG_gs_paging_len = 3;
const unsigned int MT6351_PMIC_REG_gs_early_suspend_idle_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_early_suspend_idle = MT6351_PMIC_REG_gs_early_suspend_idle_data;
unsigned int MT6351_PMIC_REG_gs_early_suspend_idle_len = 3;
const unsigned int MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_s_flightmode_suspend_mode = MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_data;
unsigned int MT6351_PMIC_REG_gs_s_flightmode_suspend_mode_len = 3;
const unsigned int MT6351_PMIC_REG_gs_mp3_play_data[] = {
	/* Address     Mask        Golden Setting Value */
	0x00A2, 0xE000, 0x0000,	/* AUXADC_CON0 */
};

const unsigned int *MT6351_PMIC_REG_gs_mp3_play = MT6351_PMIC_REG_gs_mp3_play_data;
unsigned int MT6351_PMIC_REG_gs_mp3_play_len = 3;
