ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y	:=  bmi160_acc.o

