--- drivers/gpu/arm/midgard/backend/gpu/Kbuild
+++ drivers/gpu/arm/midgard/backend/gpu/Kbuild
@@ -43,16 +43,7 @@
         backend/gpu/mali_kbase_jm_rb.o
 endif
 
-ifeq ($(MALI_CUSTOMER_RELEASE),0)
-    mali_kbase-y += \
-        backend/gpu/mali_kbase_pm_always_on_demand.o
-endif
 
 mali_kbase-$(CONFIG_MALI_DEVFREQ) += \
     backend/gpu/mali_kbase_devfreq.o
 
-# Dummy model
-mali_kbase-$(CONFIG_MALI_NO_MALI) += backend/gpu/mali_kbase_model_dummy.o
-mali_kbase-$(CONFIG_MALI_NO_MALI) += backend/gpu/mali_kbase_model_linux.o
-# HW error simulation
-mali_kbase-$(CONFIG_MALI_NO_MALI) += backend/gpu/mali_kbase_model_error_generator.o
