
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-$(CONFIG_MOTO_FLATUP)	+=	moto_flatup/
obj-$(CONFIG_MOTO_FLATDOWN)	+=	moto_flatdown/
obj-$(CONFIG_MOTO_STOWED)	+=	moto_stowed/
obj-$(CONFIG_MOTO_CAMGEST)	+=	moto_camgest/
obj-$(CONFIG_MOTO_CHOPCHOP)	+=	moto_chopchop/
obj-$(CONFIG_MOTO_GLANCE)	+=	moto_glance/
obj-$(CONFIG_MOTO_LTV)	        +=	moto_ltv/
obj-$(CONFIG_MOTO_FTM)	        +=	moto_ftm/
obj-$(CONFIG_MOTO_OFFBODY)     +=	moto_offbody/
obj-$(CONFIG_MOTO_LTS)	        +=	moto_lts/
