#!/bin/bash

CORRECT_CONFIG_FILE="./drivers/misc/mediatek/kcrs/correct_config.csv"
BLACK_PROJECT_LIST="./drivers/misc/mediatek/kcrs/project_not_review.txt"

function usage ()
{
    echo $0 'Check for kernel config with correct_config.csv'
    echo 'Usage:'
    echo '  '$0' [-c] [-h]'
    echo '      -c  commit ID to check(HEAD if not set)'
    echo '	-u  flag to decide warning only or return error'
    echo '      -h  This help'
    exit 0
}

function remove_value_note
{
    INPUT_VALUE=$1
    RESULT_VALUE=$(echo $INPUT_VALUE | sed 's/(USER)//g')
    RESULT_VALUE=$(echo $RESULT_VALUE | sed 's/(PLATFORM)//g')
    RESULT_VALUE=$(echo $RESULT_VALUE | sed 's/(USER;PROJECT)//g')
    RESULT_VALUE=$(echo $RESULT_VALUE | sed 's/(NOT_USER)//g')
    RESULT_VALUE=$(echo $RESULT_VALUE | sed 's/(PROJECT)//g')
    echo $RESULT_VALUE
}

PDL_CONFIG=""
PDL_VALUE=""
function parse_defconfig_line
{
    PDL_VALUE=""
    PDL_CONFIG=""
    PARSE_LINE=$1

    PDL_CONFIG=$(echo $PARSE_LINE | sed 's/^# //g' | awk -F" |=" '{ print $1 }')
    if [ "$(echo $PARSE_LINE | grep "is not set")" != "" ]; then
        PDL_VALUE="N"
    elif [ "$(echo $PARSE_LINE | grep \")" != "" ]; then
        # from string to X
        PDL_VALUE="$(echo $PARSE_LINE | awk -F\" '{ print $2 }')"
    else
        # from value to X
        PDL_VALUE=$(echo $PARSE_LINE | awk -F= '{ print $2 }')
    fi

    if [ "$PARSE_LINE" == "" ]; then
        PDL_VALUE="X"
    fi
}

PCI_RESULT=""
function parse_config_item
{
    PARSE_LINE=$1
    PARSE_INDEX=$2

    TEMP_LINE=$(echo $PARSE_LINE | sed 's/\r//g')
    for ((TEMP_INDEX=1; TEMP_INDEX<=$PARSE_INDEX; TEMP_INDEX++))
    do
        PCI_RESULT=$(echo $TEMP_LINE | grep -o "^[ ]*\"[^\"]*\"[ ]*,")
        if [ "$PCI_RESULT" == "" ]; then
            PCI_RESULT=$(echo $TEMP_LINE | grep -o "^[ ]*\"[^\"]*\"[ ]*$")
        else
            TEMP_LINE=$(echo $TEMP_LINE | sed -e 's/^[ ]*\"[^\"]*\"[ ]*,//g')
            continue
        fi
        if [ "$PCI_RESULT" == "" ]; then
            PCI_RESULT=$(echo $TEMP_LINE | grep -o "^[^,]*,")
        else
            TEMP_LINE=$(echo $TEMP_LINE | sed -e 's/^[ ]*\"[^\"]*\"[ ]*$//g')
            continue
        fi
        if [ "$PCI_RESULT" == "" ]; then
            PCI_RESULT=$(echo $TEMP_LINE | grep -o "^[^,]*")
        fi
        SED_STRING="s/^$PCI_RESULT//g"
        TEMP_LINE=$(echo $TEMP_LINE | sed -e "$SED_STRING")
    done
    PCI_RESULT=$(echo $PCI_RESULT | sed 's/,$//g')
}

if [ $# == 0 ]; then
    # check local modification
    echo "check local modification"
fi

GIT_COMMIT_ID=""
UPLOAD_MSG_TO_GERRIT=""
GIT_CMD="git diff --cached"
while getopts "c:uh" opt; do
    case $opt in
      c)
        GIT_COMMIT_ID=$OPTARG
        GIT_CMD="git show"
        ;;
      u)
        # send message to gerrit instead of return error
        # only for preflight server, mark this to block preflight
	# unmark it to show warning message in gerrit only
        # UPLOAD_MSG_TO_GERRIT="yes"
        ;;
      h)
        usage
        ;;
    esac
done

TEMPFILE_PATH=$(mktemp -t check_kernel_config_temp.$$.XXXXX.txt)
RETURN=0

declare -A CONFIG_TABLE_HASH
declare -A CORRECT_TABLE_HASH
declare -A DEBUG_USER_TABLE_HASH

# check if there is not correct_config.csv file
if [ ! -f $CORRECT_CONFIG_FILE ]; then
    exit 0
fi

SKIP="0"
GREP_CMD=""
if [ -f $BLACK_PROJECT_LIST ]; then
    while read LINE
    do
        if [ "$LINE" != "" ]; then
            if [ "$SKIP" == "0" ]; then
                SKIP="1"
                GREP_CMD=$GREP_CMD"/$LINE"
            else
                GREP_CMD=$GREP_CMD"\|/$LINE"
            fi
        fi
    done < $BLACK_PROJECT_LIST
fi
GIT_FILE_LIST=$($GIT_CMD --pretty="format:" --name-status $GIT_COMMIT_ID arch/arm/configs arch/arm64/configs | grep ^M | grep -v "$GREP_CMD" | awk '{ print $2 }')

CORRECT_CONFIG_HEADER=$(head -n 1 $CORRECT_CONFIG_FILE)
CURRENT_PLATFORM_LIST=$(echo $CORRECT_CONFIG_HEADER | sed 's/^.*NOTE,//g' | sed 's/,/ /g')
PROJECT_CONFIG_LIST=""
for FILE in $GIT_FILE_LIST
do
    if [ ! -f $FILE ]; then
        continue
    fi

    # defconfig file architecture and platform
    FILE_PLATFORM=$(grep "CONFIG_ARCH_MT....[A-Z]*=y" $FILE | awk -F= '{ print $1 }' | sed 's/CONFIG_ARCH_MT//g')
    # skip not CONFIG_ARCH_MTxxxxx=y platform
    if [ "$FILE_PLATFORM" == "" ]; then
        # try again if this is 4.4, ARCH_MTXXXX rename to MACH_MTXXXX
        FILE_PLATFORM=$(grep "CONFIG_MACH_MT....[A-Z]*=y" $FILE | awk -F= '{ print $1 }' | sed 's/CONFIG_MACH_MT//g')
        if [ "$FILE_PLATFORM" == "" ]; then
            echo "skip file $FILE"
            continue
        fi
    fi
    if [ "$(echo $FILE | grep "arch/arm64/configs")" != "" ]; then
        FILE_PLATFORM=$FILE_PLATFORM"_64"
    fi

    # skip not reviewed platform
    if [ "$(echo $CURRENT_PLATFORM_LIST | grep "$FILE_PLATFORM\b")" == "" ]; then
        continue
    fi

    #build hash table
    CONFIG_LIST=""
    CONFIG_VALUE=""
    while read LINE
    do
        if [ "$(echo $LINE | grep "#")" == "" ]; then
            CONFIG_NAME=$(echo $LINE | awk '{ print $1 }' | sed 's/-//g' | sed 's/=.*//g' )
        else
            CONFIG_NAME=$(echo $LINE | awk '{ print $2 }' | sed 's/-//g')
        fi
        if [ "$(echo $LINE | grep "is not set")" != "" ]; then
            # from N to X, X : means depends
            ORI_VALUE="N"
        elif [ "$(echo $LINE | grep \")" != "" ]; then
            # from string to X
            ORI_VALUE="$(echo $LINE | awk -F\" '{ print $2 }')"
        else
            # from value to X
            ORI_VALUE=$(echo $LINE | awk -F= '{ print $2 }')
            # support kernel module m=y
            if [ "$ORI_VALUE" == "m" ]; then
                ORI_VALUE="y"
            fi
        fi
        CONFIG_TABLE_HASH[$CONFIG_NAME,CONFIG]="$CONFIG_NAME"
        CONFIG_TABLE_HASH[$CONFIG_NAME,ORI_VALUE]="$ORI_VALUE"
        CONFIG_TABLE_HASH[$CONFIG_NAME,VALUE]="X"
        CONFIG_TABLE_HASH[$CONFIG_NAME,LINE]="$LINE"
        CONFIG_VALUE="X"
        CONFIG_LIST="$CONFIG_LIST$CONFIG_NAME "
    done < <($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE | grep "^-.*CONFIG_")

    while read LINE
    do
        if [ "$(echo $LINE | grep "#")" == "" ]; then
            CONFIG_NAME=$(echo $LINE | awk '{ print $1 }' | sed 's/+//g' | sed 's/=.*//g')
        else
            CONFIG_NAME=$(echo $LINE | awk '{ print $2 }' | sed 's/+//g')
        fi

        if [ "$(echo $LINE | grep "is not set")" != "" ]; then
            CONFIG_VALUE="N"
        elif [ "$(echo $LINE | grep \")" != "" ]; then
            CONFIG_VALUE="$(echo $LINE | awk -F\" '{ print $2 }')"
        else
            CONFIG_VALUE=$(echo $LINE | awk -F= '{ print $2 }')
            # support kernel module m=y
            if [ "$CONFIG_VALUE" == "m" ]; then
                CONFIG_VALUE="y"
            fi
        fi
        CONFIG_TABLE_HASH[$CONFIG_NAME,CONFIG]="$CONFIG_NAME"
        CONFIG_TABLE_HASH[$CONFIG_NAME,VALUE]="$CONFIG_VALUE"
        CONFIG_TABLE_HASH[$CONFIG_NAME,LINE]="$LINE"
        if [ "$(echo $CONFIG_LIST | grep "$CONFIG_NAME\b")" == "" ];then
            CONFIG_LIST="$CONFIG_LIST$CONFIG_NAME "
        fi
    done < <($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE | grep "^+.*CONFIG_")

    for CONFIG in $CONFIG_LIST
    do
        # echo "$FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]}"
        LINE=$(grep "$CONFIG," $CORRECT_CONFIG_FILE | sed 's/\r//g')
        if [ "$LINE" == "" ] && [ "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" != "X" ]; then
            echo "check_kernel_config fail" >> $TEMPFILE_PATH
            echo "$FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is new config(new config)"  >> $TEMPFILE_PATH
            $GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE | grep "^[+|-].*$CONFIG[=|\b]" >> $TEMPFILE_PATH
            echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
            echo "=====================================================================" >> $TEMPFILE_PATH
            RETURN=1
        fi

        # setup correct_table_hash
        if [ "${CORRECT_TABLE_HASH[$CONFIG,CONFIG]}" == "" ]; then
            CORRECT_TABLE_HASH[$CONFIG,CONFIG]="$CONFIG"
            TYPE=$(echo $LINE | awk -F, '{ print $2 }' | sed 's/ //g')
            CORRECT_TABLE_HASH[$CONFIG,TYPE]="$TYPE"
            OWNER=$(echo $LINE | awk -F, '{ print $3 }' | sed 's/ //g')
            CORRECT_TABLE_HASH[$CONFIG,OWNER]="$OWNER"
            NOTE=$(echo $LINE | awk -F, '{ print $4 }')
            CORRECT_TABLE_HASH[$CONFIG,NOTE]="$NOTE"

            INDEX=5
            for PLATFORM in $CURRENT_PLATFORM_LIST
            do
                if [ "$(echo $LINE | grep "\"")" != "" ]; then
                    parse_config_item "$LINE" $INDEX
                    VALUE=$(echo $PCI_RESULT | sed 's/"//g')
                else
                    VALUE=$(echo $LINE | awk -F, '{ print $'$INDEX' }')
                fi
                if [ "$TYPE" == "PROJECT" ] || [ "$TYPE" == "USER;PROJECT" ]; then
                    VALUE=$(remove_value_note "$VALUE")
                fi

                # support kernel module m=y
                if [ "$VALUE" == "m" ]; then
                    VALUE="y"
                fi
                if [ "$TYPE" == "USER;PLATFORM" ]; then
                    VALUE=$(echo $VALUE | sed 's/m(/y(/g')
                fi

                CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]="$VALUE"
                INDEX=$(($INDEX+1))
            done
        fi

        # check with correct_config.csv
        if [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "PROJECT" ]; then
            # Verify debug and release load should be the same
            DEBUG_USER_TABLE_HASH[$CONFIG,$FILE,VALUE]=${CONFIG_TABLE_HASH[$CONFIG,VALUE]}
            DEBUG_USER_TABLE_HASH[$CONFIG,$FILE,CONFIG]=$CONFIG
            PROJECT_CONFIG_LIST="$PROJECT_CONFIG_LIST$FILE:$CONFIG "
            continue
        elif [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "USER;PLATFORM" ]; then
            if [ "$(echo ${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]} | grep \(PLATFORM\))" != "" ]; then
                CORRECT_PLATFORM_VALUE=$(echo ${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]} | sed 's/(.*)$//g')
                if [ "$CORRECT_PLATFORM_VALUE" != "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                    # USER;PLATFORM platform type config value is wrong
                    echo "check_kernel_config fail" >> $TEMPFILE_PATH
                    echo "$FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(${CORRECT_TABLE_HASH[$CONFIG,TYPE]} (PLATFORM) type wrong value) " >> $TEMPFILE_PATH
                    echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                    echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                    echo "settings in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                    echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                    echo "$LINE" >> $TEMPFILE_PATH
                    echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                    echo "=====================================================================" >> $TEMPFILE_PATH
                    RETURN=1
                fi
            else
                # USER config in USER;PLATFORM type
                CORRECT_PLATFORM_VALUE=$(echo ${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]} | sed 's/(.*)$//g')
                if [ "$(echo $FILE | grep "_debug_")" != "" ]; then
                    if [ "$CORRECT_PLATFORM_VALUE" == "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                        # user type config, debug load should be different
                        echo "check_kernel_config fail" >> $TEMPFILE_PATH
                        echo "debug load $FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(USER;PLATFORM (USER) type wrong value)" >> $TEMPFILE_PATH
                        echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                        echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                        echo "settings in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                        echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                        echo "$LINE" >> $TEMPFILE_PATH
                        echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                        echo "=====================================================================" >> $TEMPFILE_PATH
                        RETURN=1
                    fi
                else
                    if [ "$CORRECT_PLATFORM_VALUE" != "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                        # user type config, user load should be the same
                        echo "check_kernel_config fail" >> $TEMPFILE_PATH
                        echo "release load $FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(USER;PLATFORM (USER) type wrong value)" >> $TEMPFILE_PATH
                        echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                        echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                        echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                        echo "$LINE" >> $TEMPFILE_PATH
                        echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                        echo "=====================================================================" >> $TEMPFILE_PATH
                        RETURN=1
                    fi
                fi
            fi
        elif [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "COMMON" ] || \
            [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "PLATFORM" ]; then
            if [ "${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" != "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                # common or platform type config value is wrong
                echo "check_kernel_config fail" >> $TEMPFILE_PATH
                echo "$FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(${CORRECT_TABLE_HASH[$CONFIG,TYPE]} type wrong value) " >> $TEMPFILE_PATH
                echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                echo "settings in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                echo "$LINE" >> $TEMPFILE_PATH
                echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                echo "=====================================================================" >> $TEMPFILE_PATH
                RETURN=1
            fi
        elif [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "USER" ]; then
            if [ "$(echo $FILE | grep "_debug_")" != "" ]; then
                if [ "${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" == "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                    # user type config, debug load should be different
                    echo "check_kernel_config fail" >> $TEMPFILE_PATH
                    echo "debug load $FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(USER type wrong value)" >> $TEMPFILE_PATH
                    echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                    echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                    echo "settings in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                    echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                    echo "$LINE" >> $TEMPFILE_PATH
                    echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                    echo "=====================================================================" >> $TEMPFILE_PATH
                    RETURN=1
                fi
            else
                if [ "${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" != "${CONFIG_TABLE_HASH[$CONFIG,VALUE]}" ]; then
                    # user type config, user load should be the same
                    echo "check_kernel_config fail" >> $TEMPFILE_PATH
                    echo "release load $FILE set $CONFIG to ${CONFIG_TABLE_HASH[$CONFIG,VALUE]} is wrong(USER type wrong value)" >> $TEMPFILE_PATH
                    echo "${CONFIG_TABLE_HASH[$CONFIG,LINE]}" >> $TEMPFILE_PATH
                    echo "correct_config.csv type=${CORRECT_TABLE_HASH[$CONFIG,TYPE]} value=${CORRECT_TABLE_HASH[$CONFIG,$FILE_PLATFORM]}" >> $TEMPFILE_PATH
                    echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                    echo "$LINE" >> $TEMPFILE_PATH
                    echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                    echo "=====================================================================" >> $TEMPFILE_PATH
                    RETURN=1
                fi
            fi
        fi
    done
done

for ITEM in $PROJECT_CONFIG_LIST
do
    FILE=$(echo $ITEM | awk -F: '{ print $1 }')
    CONFIG=$(echo $ITEM | awk -F: '{ print $2 }')
    if [ "$(echo $FILE | grep "_debug_")" == "" ]; then
        FILE_DEBUG=$(echo $FILE | sed 's/_defconfig/_debug_defconfig/g')
        FILE_USER=$FILE
    else
        FILE_USER=$(echo $FILE | sed 's/_debug_defconfig/_defconfig/g')
        FILE_DEBUG=$FILE
    fi
    if [ "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,VALUE]}" != "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,VALUE]}" ]; then
        if [ "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,CONFIG]}" != "" ] &&  \
            [ "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,CONFIG]}" != "" ]; then
            echo "check_kernel_config fail" >> $TEMPFILE_PATH
            echo "PROJECT type $CONFIG is wrong (debug user mismatch)" >> $TEMPFILE_PATH
            echo "DEBUG load $FILE_DEBUG $CONFIG is ${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,VALUE]}" >> $TEMPFILE_PATH
            echo "USER load $FILE_USER $CONFIG is ${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,VALUE]}" >> $TEMPFILE_PATH
            FILE_DEBUG_MSG=$($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE_DEBUG | grep "^[+|-].*$CONFIG[=|\b| ]")
            echo "$FILE_DEBUG : $FILE_DEBUG_MSG" >> $TEMPFILE_PATH
            FILE_USER_MSG=$($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE_USER | grep "^[+|-].*$CONFIG[=|\b| ]")
            echo "$FILE_USER : $FILE_USER_MSG" >> $TEMPFILE_PATH
            echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
            echo "=====================================================================" >> $TEMPFILE_PATH
            RETURN=1
        elif [ "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,CONFIG]}" == "" ]; then
            CONFIG_LINE=$(grep "$CONFIG[ |\=]" $FILE_DEBUG)
            parse_defconfig_line "$CONFIG_LINE"
            if [ "$PDL_VALUE" != "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,VALUE]}" ]; then
                echo "check_kernel_config fail" >> $TEMPFILE_PATH
                echo "PROJECT type $CONFIG is wrong (debug user mismatch)" >> $TEMPFILE_PATH
                echo "USER load $FILE_USER $CONFIG is ${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,VALUE]}" >> $TEMPFILE_PATH
                echo "DEBUG load $FILE_DEBUG $CONFIG is not modified in this commit" >> $TEMPFILE_PATH
                echo "DEBUG load $FILE_DEBUG $CONFIG in preflight codebase is $PDL_VALUE" >> $TEMPFILE_PATH
                FILE_USER_MSG=$($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE_USER | grep "^[+|-].*$CONFIG[=|\b| ]")
                echo "$FILE_USER : $FILE_USER_MSG" >> $TEMPFILE_PATH
                echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                echo "=====================================================================" >> $TEMPFILE_PATH
                RETURN=1
            fi
        elif [ "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_USER,CONFIG]}" == "" ]; then
            CONFIG_LINE=$(grep "$CONFIG[ |\=]" $FILE_USER)
            parse_defconfig_line "$CONFIG_LINE"
            if [ "$PDL_VALUE" != "${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,VALUE]}" ]; then
                echo "check_kernel_config fail" >> $TEMPFILE_PATH
                echo "PROJECT type $CONFIG is wrong (debug user mismatch)" >> $TEMPFILE_PATH
                echo "DEBUG load $FILE_DEBUG $CONFIG is ${DEBUG_USER_TABLE_HASH[$CONFIG,$FILE_DEBUG,VALUE]}" >> $TEMPFILE_PATH
                echo "USER load $FILE_USER $CONFIG is not modified in this commit" >> $TEMPFILE_PATH
                echo "USER load $FILE_USER $CONFIG in preflight codebase is $PDL_VALUE" >> $TEMPFILE_PATH
                FILE_DEBUG_MSG=$($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $FILE_DEBUG | grep "^[+|-].*$CONFIG[=|\b| ]")
                echo "$FILE_DEBUG : $FILE_DEBUG_MSG" >> $TEMPFILE_PATH
                echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                echo "=====================================================================" >> $TEMPFILE_PATH
                RETURN=1
            fi
        fi
    fi
done

# check correct_config.csv format
GIT_MODIFY_CORRECT=$($GIT_CMD --pretty="format:" --name-status $GIT_COMMIT_ID $CORRECT_CONFIG_FILE)
if [ "$GIT_MODIFY_CORRECT" != "" ]; then
    while read LINE
    do
        LINE=$(echo $LINE | sed 's/\r//g')
        MOD_LINE=$(echo $LINE | sed 's/^+//g')
        CONFIG=$(echo $MOD_LINE | awk -F, '{ print $1 }' | sed 's/ //g')
        if [ "${CORRECT_TABLE_HASH[$CONFIG,CONFIG]}" == "" ]; then
            CORRECT_TABLE_HASH[$CONFIG,CONFIG]="$CONFIG"
            TYPE=$(echo $MOD_LINE | awk -F, '{ print $2 }' | sed 's/ //g')
            CORRECT_TABLE_HASH[$CONFIG,TYPE]="$TYPE"
            OWNER=$(echo $MOD_LINE | awk -F, '{ print $3 }' | sed 's/ //g')
            CORRECT_TABLE_HASH[$CONFIG,OWNER]="$OWNER"
            NOTE=$(echo $MOD_LINE | awk -F, '{ print $4 }')
            CORRECT_TABLE_HASH[$CONFIG,NOTE]="$NOTE"

            INDEX=5
            for PLATFORM in $CURRENT_PLATFORM_LIST
            do
                if [ "$(echo $MOD_LINE | grep "\"")" != "" ]; then
                    parse_config_item "$MOD_LINE" $INDEX
                    VALUE=$(echo $PCI_RESULT | sed 's/"//g')
                else
                    VALUE=$(echo $MOD_LINE | awk -F, '{ print $'$INDEX' }')
                fi
                CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]="$VALUE"
                INDEX=$(($INDEX+1))
            done
        fi
        if [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "COMMON" ]; then
            SKIP="0"
            COMMON_VALUE=""
            for PLATFORM in $CURRENT_PLATFORM_LIST
            do
                if [ "$SKIP" == "0" ]; then
                    COMMON_PLATFORM=$PLATFORM
                    COMMON_VALUE=${CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]}
                    SKIP="1"
                else
                    if [ "${CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]}" != "$COMMON_VALUE" ]; then
                        echo "check_kernel_config fail" >> $TEMPFILE_PATH
                        echo "$CORRECT_CONFIG_FILE set $CONFIG to ${CORRECT_TABLE_HASH[$CONFIG,TYPE]} is wrong(correct_config.csv format wrong)" >> $TEMPFILE_PATH
                        echo "$COMMON_PLATFORM is $COMMON_VALUE , $PLATFORM is ${CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]}" >> $TEMPFILE_PATH
                        echo "all the platform value of COMMON type in correct_config.csv should be the same" >> $TEMPFILE_PATH
                        echo "your change in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                        echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                        echo "$MOD_LINE" >> $TEMPFILE_PATH
                        echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                        echo "=====================================================================" >> $TEMPFILE_PATH
                        RETURN=1
                        break
                    fi
                fi
            done
        elif [ "${CORRECT_TABLE_HASH[$CONFIG,TYPE]}" == "USER;PLATFORM" ]; then
            COMMON_VALUE=""
            for PLATFORM in $CURRENT_PLATFORM_LIST
            do
                USER_PLATFORM_SUBVALUE="(USER)$\|(PLATFORM)$"
                if [ "$(echo ${CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]} | grep $USER_PLATFORM_SUBVALUE)" == "" ]; then
                    echo "check_kernel_config fail" >> $TEMPFILE_PATH
                    echo "$CORRECT_CONFIG_FILE set $CONFIG to ${CORRECT_TABLE_HASH[$CONFIG,TYPE]} is wrong(correct_config.csv format wrong)" >> $TEMPFILE_PATH
                    echo "$PLATFORM set ${CORRECT_TABLE_HASH[$CONFIG,$PLATFORM]}" >> $TEMPFILE_PATH
                    echo "all the platform value of USER;PLATFORM type in correct_config.csv should have subvalue (USER) or (PLATFORM)" >> $TEMPFILE_PATH
                    echo "your change in $CORRECT_CONFIG_FILE" >> $TEMPFILE_PATH
                    echo "$CORRECT_CONFIG_HEADER" >> $TEMPFILE_PATH
                    echo "$MOD_LINE" >> $TEMPFILE_PATH
                    echo "please reference http://wiki.mediatek.inc/display/OSS10SS15/check_kernel_config+result" >> $TEMPFILE_PATH
                    echo "=====================================================================" >> $TEMPFILE_PATH
                    RETURN=1
                    break
                fi
            done
        fi

    done < <($GIT_CMD --pretty="format:" $GIT_COMMIT_ID $CORRECT_CONFIG_FILE | grep "^+.*CONFIG_")
fi

if [ "$RETURN" != "0" ] && [ -f $TEMPFILE_PATH ]; then

    cat $TEMPFILE_PATH
    if [ "$UPLOAD_MSG_TO_GERRIT" == "yes" ]; then
    	PREFLIGHT_FOLDER="/proj/srv_gghpbm/workspace/Preflight_Git_Kernel/ws/$BUILD_NUMBER"
	    GERRIT_FILE_PATH=$(ls $PREFLIGHT_FOLDER/gerrit*)
	    GERRIT_CHANGE_NUMBER=$(echo $GERRIT_FILE_PATH | awk -F/ '{ print $NF }' | sed 's/^gerrit_//g' | sed 's/\.properties//g')
	    GERRIT_PATCHSET_REVISION=$(cat $GERRIT_FILE_PATH | grep revision | awk -F= '{ print $2 }' | sed 's/ //g')
        if [ "$GERRIT_CHANGE_NUMBER" != "" ] && [ "$GERRIT_PATCHSET_REVISION" != "" ]; then
            python /mtkeda/CI/Gerrit-ACL/gerrit_review.py \
            -s http://gerrit.mediatek.inc:8080 \
            -u "adm_jenkins" \
            -c $GERRIT_CHANGE_NUMBER \
            -r $GERRIT_PATCHSET_REVISION \
            -m $TEMPFILE_PATH
        else
            echo "BUILD_NUMBER : $BUILD_NUMBER"
            echo "GERRIT_FILE_PATH : $GERRIT_FILE_PATH"
            echo "GERRIT_CHANGE_NUMBER : $GERRIT_CHANGE_NUMBER"
            echo "GERRIT_PATCHSET_REVISION : $GERRIT_PATCHSET_REVISION"
        fi
        # don't stop preflight if we have warning message
        RETURN=0
    fi
    rm $TEMPFILE_PATH
fi

exit $RETURN

