###################################################################
#[mach_obj][HACC]: if TEE is enabled, HACC is done in secure world.
###################################################################
mach_obj += $(asf_link)/mach/hacc_lib.o
mach_obj += $(asf_link)/mach/hacc_export.o
mach_obj += $(asf_link)/mach/hacc_hk.o
mach_obj += $(asf_link)/mach/hacc_sk.o
mach_obj += $(asf_link)/mach/sec_lib.o

ccflags-y += -I$(src)/$(asf_link)/asf_inc
