
#MTK port custom Kbuild
#To Add 1.environment variable
include $(src)/../../Kbuild-mtk-custom-env

#ccflags-y += -DMTK_GPU_APM
ccflags-$(CONFIG_MTK_GPU_SPM_DVFS_SUPPORT) += -DMTK_GPU_SPM
#ccflags-y += -DMTK_GPU_DPM
#ccflags-y += -DMTK_GPU_OCP

obj-y += mtk_config_platform.o
obj-y += mtk_kbase_spm.o
obj-y += mtk_kbase_spm_fw.o
obj-y += mtk_kbase_spm_hal.o

