/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *   custom_emi.h
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *   This Module defines the EMI (external memory interface) related setting.
 *
 * Author:
 * -------
 *  EMI auto generator V0.01
 *
 *   Memory Device database last modified on 2015/4/2
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * WARNING!!!  WARNING!!!   WARNING!!!  WARNING!!!  WARNING!!!  WARNING!!! 
 * This file is generated by EMI Auto-gen Tool.
 * Please do not modify the content directly!
 * It could be overwritten!
 *============================================================================
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __CUSTOM_EMI__
#define __CUSTOM_EMI__

#include "emi.h"

#define COMBO_LPDDR2 (0+0)
#define COMBO_LPDDR3 (0+6)
#define COMBO_PCDDR3 (0+0)
#ifndef CONFIG_CX885_MAINBOARD
#define NUM_EMI_RECORD (6)
#else
#define NUM_EMI_RECORD (9)
#endif

int num_of_emi_records = NUM_EMI_RECORD ;

EMI_SETTINGS emi_settings[] =
{
     #ifdef CONFIG_CX885_MAINBOARD
	//H9CKNNNBKTMRPR
	{
		"H9CKNNNBKTMRPR",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0x20102017,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},		
		{0x80000000,0,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000006,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//K3QF3F30BM
	{
		"K3QF3F30BM",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0x20102017,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x80000000,0,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000001,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//MT52L256M64D2GN
	{
		"MT52L256M64D2GN",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0x20102017,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x80000000,0,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x000000FF,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	#endif
	//K3QF6F60AM
	{
		"K3QF6F60AM",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x33330000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x60000000,0x60000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000001,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//EDFP164A3PD
	{
		"EDFP164A3PD",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x33330000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x60000000,0x60000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000003,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//H9CKNNNDATMUPR
	{
		"H9CKNNNDATMUPR",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x33330000,		/* EMI_CONH_VAL */
		{{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x60000000,0x60000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000006,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	
//MT52L512M64D4GN
	{
                "MT52L512M64D4GN",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
                {{0x06090320,0x19491101,0x0B060201,0x060C0306,0x22556560,0x00150044,0x00000000}},
		{0x80000000,0x80000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x000000FF,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//H9CKNNNCPTMRPR
	{
		"H9CKNNNCPTMRPR",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
		{{0x06090320,		/* U 00 */
		0x19491101,		/* U 01 */
		0x0B060201,		/* U 02 */
		0x060C0306,		/* U 03 */
		0x22556560,		/* U 04 */
		0x00150044,		/* U 05 */
		0x00000000}},		/* U 06 */
		{0x80000000,0x80000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000006,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,
	//K3QF4F40BM
	{
		"K3QF4F40BM",
		0x1,		/* sub_version */
		0x0003,		/* TYPE */
		0,		/* EMMC ID/FW ID checking length */
		0,		/* FW length */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* NAND_EMMC_ID */
		{0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},		/* FW_ID */
		0xa053a057,		/* EMI_CONA_VAL */
		0x00000000,		/* EMI_CONH_VAL */
		{{0x06090320,		/* U 00 */
		0x19491101,		/* U 01 */
		0x0B060201,		/* U 02 */
		0x060C0306,		/* U 03 */
		0x22556560,		/* U 04 */
		0x00150044,		/* U 05 */
		0x00000000}},		/* U 06 */
		{0x80000000,0x80000000,0,0},		/* DRAM RANK SIZE */
		0x04210000,		/* EMI_CONF_VAL */
		{0,0,0,0,0,0,0,0,0},		/* reserved 9 */
		0x00000001,		/* LPDDR3_MODE_REG5 */
		0,		/* PIN_MUX_TYPE for tablet */
	} ,

};

#endif /* __CUSTOM_EMI__ */
