#MTK port custom Kbuild
#To Add 1.environment variable
include $(src)/../../Kbuild-mtk-custom-env

# Don't power-off when early porting
ccflags-y += -DMTK_GPU_EARLY_PORTING

obj-y += mtk_config_platform.o
