ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT910/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT910/include
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt9xx_driver.o
obj-y	+=  goodix_tool.o
obj-y	+=  gt9xx_update.o

