#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#*******add oufeiguang lcm for A158 ---lenovo@lenovo.com begin at 20161109********
#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += nt35512_cmi_720p_oufeiguang.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
#*******add oufeiguang lcm for A158 ---lenovo@lenovo.com end at 20161109********

