obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += vdec_mpeg4_if.o vdec_mpeg4_vpu.o

ccflags-y += \
    -I$(srctree)/include \
    -I$(srctree)/drivers/media/platform/mediatek \
    -I$(srctree)/drivers/media/platform/mediatek/include \
    -I$(srctree)/drivers/media/platform/mediatek/mpeg4_dec \
    -I$(srctree)/drivers/media/platform/mediatek/mpeg4_dec/vpu
