#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

subdir-ccflags-y += \
		-I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM) \
		-I$(srctree)/drivers/misc/mediatek/video/include/                     \
		-I$(srctree)/drivers/misc/mediatek/video/common/                      \
		-I$(srctree)/drivers/misc/mediatek/video/common/rdma10/               \
		-I$(srctree)/drivers/misc/mediatek/video/common/wdma10/               \
		-I$(srctree)/drivers/misc/mediatek/cmdq/v2/                           \
		-I$(srctree)/drivers/misc/mediatek/cmdq/v2/$(MTK_PLATFORM)/           \
		-I$(srctree)/drivers/misc/mediatek/externaldisplay/$(MTK_PLATFORM)    \
		-I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/include/mach/ \
		-I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)         \
		-I$(srctree)/drivers/misc/mediatek/base/power/include/spm_v1/         \
		-I$(srctree)/drivers/misc/mediatek/base/power/include/                \
		-I$(srctree)/drivers/misc/mediatek/m4u/$(MTK_PLATFORM)/               \
		-I$(srctree)/drivers/misc/mediatek/mmp/                               \
		-I$(srctree)/drivers/misc/mediatek/sync/ \
		-I$(srctree)/drivers/misc/mediatek/lcm/inc/

obj-y += emi_mpu.o

