ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/dramc/$(MTK_PLATFORM)/
ccflags-$(CONFIG_MACH_MT6799) += -DMTK_PASR_VCORE_DVFS_CONTROL
obj-y += mtkpasr_drv.o mtkpasr_hw.o
