ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_boost
ccflags-$(CONFIG_MACH_MT6799) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6799/include/mach
ccflags-$(CONFIG_MACH_MT6759) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6759/include/mach
obj-y := usb_boost_plat.o
