#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += ek79023_dsi_wsvga_vdo.o
obj-y += lcm_drv_ek79023_dsi_wsvga_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


