/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef __MTK_CM_MGR_PLATFORM_REG_H__
#define __MTK_CM_MGR_PLATFORM_REG_H__

/*
 * BIT Operation
 */
#define CM_BIT(_bit_) \
	(unsigned int)(1U << (_bit_))
#define CM_BITS(_bits_, _val_) \
	((((unsigned int) -1 >> (31 - ((1) ? _bits_))) & \
	  ~((1U << ((0) ? _bits_)) - 1)) & \
	 ((_val_)<<((0) ? _bits_)))
#define CM_BITMASK(_bits_) \
	(((unsigned int) -1 >> (31 - ((1) ? _bits_))) & \
	 ~((1U << ((0) ? _bits_)) - 1))
#define CM_GET_BITS_VAL(_bits_, _val_) \
	(((_val_) & (CM_BITMASK(_bits_))) >> ((0) ? _bits_))
#define CM_NAME_VAL(_name_, _val_) \
	(_val_ << _name_##_SHIFT)
#define CM_GET_NAME_VAL(_reg_val_, _name_) \
	((_reg_val_) & (_name_##_MASK))
#define CM_GET_NAME_VAL_0(_reg_val_, _name_) \
	(((_reg_val_) & (_name_##_MASK)) >> _name_##_SHIFT)
#define CM_SET_NAME_VAL(_reg_val_, _name_, _val_) \
	(((_reg_val_) & ~(_name_##_MASK)) | \
	 ((_val_ << _name_##_SHIFT) & (_name_##_MASK)))

#undef MCUSYS_MP0
#define MCUSYS_MP0 mcucfg_mp0_counter_base

#define STALL_INFO_CONF(x) (MCUSYS_MP0 + 0x800 * (x) + 0x238)

#define CPU_AVG_STALL_RATIO(x) (MCUSYS_MP0 + 0x800 * (x) + 0x700)
#define CPU_AVG_STALL_DEBUG_CTRL(x) (MCUSYS_MP0 + 0x800 * (x) + 0x704)
#define CPU_AVG_STALL_FMETER_STATUS(x) (MCUSYS_MP0 + 0x800 * (x) + 0x708)
#define CPU_AVG_STALL_RATIO_CTRL(x) (MCUSYS_MP0 + 0x800 * (x) + 0x710)
#define CPU_AVG_STALL_COUNTER(x) (MCUSYS_MP0 + 0x800 * (x) + 0x714)

#define MP0_CPU_NONWFX_CTRL(x) (MCUSYS_MP0 + 0x8 * (x) + 0x8500)
#define MP0_CPU_NONWFX_CNT(x) (MCUSYS_MP0 + 0x8 * (x) + 0x8504)

/* STALL_INFO_CONF */
#define CPU_STALL_CACHE_OPT_LSB CM_BIT(6)
#define CPU_STALL_CACHE_OPT_SHIFT 6
#define CPU_STALL_CACHE_OPT_MASK CM_BITMASK(10:6)
/* CPU_AVG_STALL_RATIO */
#define RG_CPU_AVG_STALL_RATIO CM_BIT(0)
/* CPU_AVG_STALL_DEBUG_CTRL */
#define RG_FMETER_APB_FREQUENCY CM_BIT(0)
#define RG_STALL_INFO_SEL CM_BIT(12)
#define RG_SAMPLE_RATIO CM_BIT(16)
/* CPU_AVG_STALL_FMETER_STATUS */
#define RO_FMETER_OUTPUT CM_BIT(0)
#define RO_FMETER_LOW CM_BIT(12)
/* CPU_AVG_STALL_RATIO_CTRL */
#define RG_CPU_AVG_STALL_RATIO_EN CM_BIT(0)
#define RG_CPU_AVG_STALL_RATIO_RESTART CM_BIT(1)
#define RG_CPU_STALL_COUNTER_EN CM_BIT(4)
#define REMOVED_RG_CPU_NON_WFX_COUNTER_EN CM_BIT(5)
#define RG_CPU_STALL_COUNTER_RESET CM_BIT(6)
#define REMOVED_RG_CPU_NON_WFX_COUNTER_RESET CM_BIT(7)
#define RG_MP0_AVG_STALL_PERIOD CM_BIT(8)
#define RG_FMETER_MIN_FREQUENCY CM_BIT(12)
#define RG_FMETER_EN CM_BIT(24)
/* CPU_AVG_STALL_COUNTER */
#define RO_CPU_STALL_COUNTER CM_BIT(0)
/* MP0_CPU0_NONWFX_CTRL */
#define RG_CPU0_NON_WFX_COUNTER_EN CM_BIT(0)
#define RG_CPU0_NON_WFX_COUNTER_RESET CM_BIT(4)

#define RG_MP0_AVG_STALL_PERIOD_1MS CM_BITS(11:8, 0x8)
#define RG_MP0_AVG_STALL_PERIOD_2MS CM_BITS(11:8, 0x9)
#define RG_MP0_AVG_STALL_PERIOD_4MS CM_BITS(11:8, 0xa)
#define RG_MP0_AVG_STALL_PERIOD_8MS CM_BITS(11:8, 0xb)
#define RG_MP0_AVG_STALL_PERIOD_10MS CM_BITS(11:8, 0xc)
#define RG_MP0_AVG_STALL_PERIOD_20MS CM_BITS(11:8, 0xd)
#define RG_MP0_AVG_STALL_PERIOD_40MS CM_BITS(11:8, 0xe)
#define RG_MP0_AVG_STALL_PERIOD_80MS CM_BITS(11:8, 0xf)

#undef CM_cm_emi_reg_base
#define CM_cm_emi_reg_base cm_emi_reg_base

#define EMI_LTCT0 (cm_emi_reg_base + 0x6B0)
#define EMI_THRO_PRD3 (cm_emi_reg_base + 0x87C)
#define EMI_THRO_CTRL1 (cm_emi_reg_base + 0x858)
#define EMI_THRO_ST10 (cm_emi_reg_base + 0x9AC)
#define EMI_THRO_LAT57 (cm_emi_reg_base + 0xB68)
#define EMI_THRO_LAT58 (cm_emi_reg_base + 0xB6C)
#define EMI_THRO_LAT59 (cm_emi_reg_base + 0xB70)
#define EMI_THRO_LAT60 (cm_emi_reg_base + 0xB74)
#define EMI_THRO_LAT61 (cm_emi_reg_base + 0xB78)
#define EMI_THRO_LAT62 (cm_emi_reg_base + 0xB7C)
#define EMI_THRO_LAT63 (cm_emi_reg_base + 0xB80)
#define EMI_THRO_LAT64 (cm_emi_reg_base + 0xB84)
#define EMI_THRO_LAT65 (cm_emi_reg_base + 0xB88)
#define EMI_THRO_LAT66 (cm_emi_reg_base + 0xB8C)
#define EMI_THRO_LAT67 (cm_emi_reg_base + 0xB90)
#define EMI_THRO_LAT68 (cm_emi_reg_base + 0xB94)
#define EMI_THRO_LAT69 (cm_emi_reg_base + 0xB98)
#define EMI_THRO_LAT70 (cm_emi_reg_base + 0xB9C)
#define EMI_THRO_LAT85 (cm_emi_reg_base + 0xBD8)
#define EMI_THRO_LAT86 (cm_emi_reg_base + 0xBDC)
#define EMI_THRO_LAT87 (cm_emi_reg_base + 0xBE0)
#define EMI_THRO_LAT88 (cm_emi_reg_base + 0xBE4)
#define EMI_THRO_LAT89 (cm_emi_reg_base + 0xBE8)
#define EMI_THRO_LAT90 (cm_emi_reg_base + 0xBEC)
#define EMI_THRO_LAT91 (cm_emi_reg_base + 0xBF0)
#define EMI_THRO_LAT92 (cm_emi_reg_base + 0xBF4)
#define EMI_THRO_LAT93 (cm_emi_reg_base + 0xBF8)
#define EMI_THRO_LAT94 (cm_emi_reg_base + 0xBFC)
#define EMI_THRO_LAT95 (cm_emi_reg_base + 0xC00)
#define EMI_THRO_LAT96 (cm_emi_reg_base + 0xC04)
#define EMI_THRO_LAT97 (cm_emi_reg_base + 0xC08)
#define EMI_THRO_LAT98 (cm_emi_reg_base + 0xC0C)
#define EMI_THRO_LAT99 (cm_emi_reg_base + 0xC10)
#define EMI_THRO_LAT100 (cm_emi_reg_base + 0xC14)
#define EMI_THRO_LAT101 (cm_emi_reg_base + 0xC18)
#define EMI_THRO_LAT102 (cm_emi_reg_base + 0xC1C)
#define EMI_THRO_LAT103 (cm_emi_reg_base + 0xC20)
#define EMI_THRO_LAT104 (cm_emi_reg_base + 0xC24)
#define EMI_THRO_LAT105 (cm_emi_reg_base + 0xC28)
#define EMI_THRO_LAT106 (cm_emi_reg_base + 0xC2C)
#define EMI_THRO_LAT107 (cm_emi_reg_base + 0xC30)
#define EMI_THRO_LAT108 (cm_emi_reg_base + 0xC34)
#define EMI_THRO_LAT109 (cm_emi_reg_base + 0xC38)
#define EMI_THRO_LAT110 (cm_emi_reg_base + 0xC3C)
#define EMI_THRO_LAT111 (cm_emi_reg_base + 0xC40)
#define EMI_THRO_LAT112 (cm_emi_reg_base + 0xC44)
#define EMI_THRO_PRD4 (cm_emi_reg_base + 0xC48)

/* EMI_LTCT0 */
#define LT_INT_EN_LSB CM_BIT(0)
#define LT_INT_EN_SHIFT 0
#define LT_INT_EN_MASK CM_BITMASK(0:0)
#define LT_INT_MASK_LSB CM_BIT(1)
#define LT_INT_MASK_SHIFT 1
#define LT_INT_MASK_MASK CM_BITMASK(1:1)
/* EMI_THRO_CTRL1 */
#define THRO_FF_REMAIN_THR_LSB CM_BIT(0)
#define THRO_FF_REMAIN_THR_SHIFT 0
#define THRO_FF_REMAIN_THR_MASK CM_BITMASK(7:0)
#define AP_URGENT_IGNORE_OS_LSB CM_BIT(14)
#define AP_URGENT_IGNORE_OS_SHIFT 14
#define AP_URGENT_IGNORE_OS_MASK CM_BITMASK(14:14)
#define AP_LAT_DVFS_UP_THR_LSB CM_BIT(16)
#define AP_LAT_DVFS_UP_THR_SHIFT 16
#define AP_LAT_DVFS_UP_THR_MASK CM_BITMASK(17:16)
#define AP_LAT_TIMER_PRD_LSB CM_BIT(20)
#define AP_LAT_TIMER_PRD_SHIFT 20
#define AP_LAT_TIMER_PRD_MASK CM_BITMASK(23:20)
#define AP_IDLE_PRD_LSB CM_BIT(24)
#define AP_IDLE_PRD_SHIFT 24
#define AP_IDLE_PRD_MASK CM_BITMASK(27:24)
/* EMI_THRO_PRD3 */
#define MD_WR_LAT_DVFS_UP_THR_LSB CM_BIT(0)
#define MD_WR_LAT_DVFS_UP_THR_SHIFT 0
#define MD_WR_LAT_DVFS_UP_THR_MASK CM_BITMASK(1:0)
#define AP_WR_LAT_DVFS_UP_THR_LSB CM_BIT(2)
#define AP_WR_LAT_DVFS_UP_THR_SHIFT 2
#define AP_WR_LAT_DVFS_UP_THR_MASK CM_BITMASK(3:2)
#define AP_WR_LAT_TIMER_PRD_LSB CM_BIT(20)
#define AP_WR_LAT_TIMER_PRD_SHIFT 20
#define AP_WR_LAT_TIMER_PRD_MASK CM_BITMASK(23:20)
#define AP_WR_IDLE_PRD_LSB CM_BIT(24)
#define AP_WR_IDLE_PRD_SHIFT 24
#define AP_WR_IDLE_PRD_MASK CM_BITMASK(27:24)
/* EMI_THRO_ST10 */
#define AP_LAT_CNT_OF_LSB CM_BIT(4)
#define AP_LAT_CNT_OF_SHIFT 4
#define AP_LAT_CNT_OF_MASK CM_BITMASK(4:4)
#define AP_LAT_CNT_UF_LSB CM_BIT(5)
#define AP_LAT_CNT_UF_SHIFT 5
#define AP_LAT_CNT_UF_MASK CM_BITMASK(5:5)
/* EMI_THRO_LAT57 */
#define AP_LAT_MARGIN0_LSB CM_BIT(0)
#define AP_LAT_MARGIN0_SHIFT 0
#define AP_LAT_MARGIN0_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT58 */
#define AP_LAT_MARGIN1_LSB CM_BIT(0)
#define AP_LAT_MARGIN1_SHIFT 0
#define AP_LAT_MARGIN1_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT59 */
#define AP_LAT_MARGIN2_LSB CM_BIT(0)
#define AP_LAT_MARGIN2_SHIFT 0
#define AP_LAT_MARGIN2_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT60 */
#define AP_LAT_MARGIN3_LSB CM_BIT(0)
#define AP_LAT_MARGIN3_SHIFT 0
#define AP_LAT_MARGIN3_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT61 */
#define AP_LAT_MARGIN4_LSB CM_BIT(0)
#define AP_LAT_MARGIN4_SHIFT 0
#define AP_LAT_MARGIN4_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT62 */
#define AP_LAT_MARGIN5_LSB CM_BIT(0)
#define AP_LAT_MARGIN5_SHIFT 0
#define AP_LAT_MARGIN5_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT63 */
#define AP_LAT_MARGIN6_LSB CM_BIT(0)
#define AP_LAT_MARGIN6_SHIFT 0
#define AP_LAT_MARGIN6_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT64 */
#define AP_LAT_MARGIN7_LSB CM_BIT(0)
#define AP_LAT_MARGIN7_SHIFT 0
#define AP_LAT_MARGIN7_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT65 */
#define AP_LAT_URGENT_THR0_LSB CM_BIT(0)
#define AP_LAT_URGENT_THR0_SHIFT 0
#define AP_LAT_URGENT_THR0_MASK CM_BITMASK(15:0)
#define AP_LAT_URGENT_THR1_LSB CM_BIT(16)
#define AP_LAT_URGENT_THR1_SHIFT 16
#define AP_LAT_URGENT_THR1_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT66 */
#define AP_LAT_URGENT_THR2_LSB CM_BIT(0)
#define AP_LAT_URGENT_THR2_SHIFT 0
#define AP_LAT_URGENT_THR2_MASK CM_BITMASK(15:0)
#define AP_LAT_URGENT_THR3_LSB CM_BIT(16)
#define AP_LAT_URGENT_THR3_SHIFT 16
#define AP_LAT_URGENT_THR3_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT67 */
#define AP_LAT_URGENT_THR4_LSB CM_BIT(0)
#define AP_LAT_URGENT_THR4_SHIFT 0
#define AP_LAT_URGENT_THR4_MASK CM_BITMASK(15:0)
#define AP_LAT_URGENT_THR5_LSB CM_BIT(16)
#define AP_LAT_URGENT_THR5_SHIFT 16
#define AP_LAT_URGENT_THR5_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT68 */
#define AP_LAT_URGENT_THR6_LSB CM_BIT(0)
#define AP_LAT_URGENT_THR6_SHIFT 0
#define AP_LAT_URGENT_THR6_MASK CM_BITMASK(15:0)
#define AP_LAT_URGENT_THR7_LSB CM_BIT(16)
#define AP_LAT_URGENT_THR7_SHIFT 16
#define AP_LAT_URGENT_THR7_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT69 */
#define AP_LAT_BUDGET0_LSB CM_BIT(0)
#define AP_LAT_BUDGET0_SHIFT 0
#define AP_LAT_BUDGET0_MASK CM_BITMASK(7:0)
#define AP_LAT_BUDGET1_LSB CM_BIT(8)
#define AP_LAT_BUDGET1_SHIFT 8
#define AP_LAT_BUDGET1_MASK CM_BITMASK(15:8)
#define AP_LAT_BUDGET2_LSB CM_BIT(16)
#define AP_LAT_BUDGET2_SHIFT 16
#define AP_LAT_BUDGET2_MASK CM_BITMASK(23:16)
#define AP_LAT_BUDGET3_LSB CM_BIT(24)
#define AP_LAT_BUDGET3_SHIFT 24
#define AP_LAT_BUDGET3_MASK CM_BITMASK(31:24)
/* EMI_THRO_LAT70 */
#define AP_LAT_BUDGET4_LSB CM_BIT(0)
#define AP_LAT_BUDGET4_SHIFT 0
#define AP_LAT_BUDGET4_MASK CM_BITMASK(7:0)
#define AP_LAT_BUDGET5_LSB CM_BIT(8)
#define AP_LAT_BUDGET5_SHIFT 8
#define AP_LAT_BUDGET5_MASK CM_BITMASK(15:8)
#define AP_LAT_BUDGET6_LSB CM_BIT(16)
#define AP_LAT_BUDGET6_SHIFT 16
#define AP_LAT_BUDGET6_MASK CM_BITMASK(23:16)
#define AP_LAT_BUDGET7_LSB CM_BIT(24)
#define AP_LAT_BUDGET7_SHIFT 24
#define AP_LAT_BUDGET7_MASK CM_BITMASK(31:24)
/* EMI_THRO_PRD4 */
#define MD_LAT_TIMER_PRD_SHF_LSB CM_BIT(0)
#define MD_LAT_TIMER_PRD_SHF_SHIFT 0
#define MD_LAT_TIMER_PRD_SHF_MASK CM_BITMASK(2:0)
#define AP_LAT_TIMER_PRD_SHF_LSB CM_BIT(16)
#define AP_LAT_TIMER_PRD_SHF_SHIFT 16
#define AP_LAT_TIMER_PRD_SHF_MASK CM_BITMASK(18:16)
#define AP_WR_LAT_TIMER_PRD_SHF_LSB CM_BIT(20)
#define AP_WR_LAT_TIMER_PRD_SHF_SHIFT 20
#define AP_WR_LAT_TIMER_PRD_SHF_MASK CM_BITMASK(22:20)
#define AP_LAT_BUDGET_SHF_LSB CM_BIT(24)
#define AP_LAT_BUDGET_SHF_SHIFT 24
#define AP_LAT_BUDGET_SHF_MASK CM_BITMASK(26:24)
/* EMI_THRO_LAT85 */
#define AP_WR_LAT_MARGIN0_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN0_SHIFT 0
#define AP_WR_LAT_MARGIN0_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT86 */
#define AP_WR_LAT_MARGIN1_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN1_SHIFT 0
#define AP_WR_LAT_MARGIN1_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT87 */
#define AP_WR_LAT_MARGIN2_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN2_SHIFT 0
#define AP_WR_LAT_MARGIN2_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT88 */
#define AP_WR_LAT_MARGIN3_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN3_SHIFT 0
#define AP_WR_LAT_MARGIN3_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT89 */
#define AP_WR_LAT_MARGIN4_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN4_SHIFT 0
#define AP_WR_LAT_MARGIN4_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT90 */
#define AP_WR_LAT_MARGIN5_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN5_SHIFT 0
#define AP_WR_LAT_MARGIN5_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT91 */
#define AP_WR_LAT_MARGIN6_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN6_SHIFT 0
#define AP_WR_LAT_MARGIN6_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT92 */
#define AP_WR_LAT_MARGIN7_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN7_SHIFT 0
#define AP_WR_LAT_MARGIN7_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT93 */
#define AP_WR_LAT_URGENT_THR0_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR0_SHIFT 0
#define AP_WR_LAT_URGENT_THR0_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR1_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR1_SHIFT 16
#define AP_WR_LAT_URGENT_THR1_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT94 */
#define AP_WR_LAT_URGENT_THR2_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR2_SHIFT 0
#define AP_WR_LAT_URGENT_THR2_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR3_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR3_SHIFT 16
#define AP_WR_LAT_URGENT_THR3_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT95 */
#define AP_WR_LAT_URGENT_THR4_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR4_SHIFT 0
#define AP_WR_LAT_URGENT_THR4_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR5_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR5_SHIFT 16
#define AP_WR_LAT_URGENT_THR5_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT96 */
#define AP_WR_LAT_URGENT_THR6_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR6_SHIFT 0
#define AP_WR_LAT_URGENT_THR6_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR7_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR7_SHIFT 16
#define AP_WR_LAT_URGENT_THR7_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT97 */
#define AP_WR_LAT_BUDGET0_LSB CM_BIT(0)
#define AP_WR_LAT_BUDGET0_SHIFT 0
#define AP_WR_LAT_BUDGET0_MASK CM_BITMASK(7:0)
#define AP_WR_LAT_BUDGET1_LSB CM_BIT(8)
#define AP_WR_LAT_BUDGET1_SHIFT 8
#define AP_WR_LAT_BUDGET1_MASK CM_BITMASK(15:8)
#define AP_WR_LAT_BUDGET2_LSB CM_BIT(16)
#define AP_WR_LAT_BUDGET2_SHIFT 16
#define AP_WR_LAT_BUDGET2_MASK CM_BITMASK(23:16)
#define AP_WR_LAT_BUDGET3_LSB CM_BIT(24)
#define AP_WR_LAT_BUDGET3_SHIFT 24
#define AP_WR_LAT_BUDGET3_MASK CM_BITMASK(31:24)
/* EMI_THRO_LAT98 */
#define AP_WR_LAT_BUDGET4_LSB CM_BIT(0)
#define AP_WR_LAT_BUDGET4_SHIFT 0
#define AP_WR_LAT_BUDGET4_MASK CM_BITMASK(7:0)
#define AP_WR_LAT_BUDGET5_LSB CM_BIT(8)
#define AP_WR_LAT_BUDGET5_SHIFT 8
#define AP_WR_LAT_BUDGET5_MASK CM_BITMASK(15:8)
#define AP_WR_LAT_BUDGET6_LSB CM_BIT(16)
#define AP_WR_LAT_BUDGET6_SHIFT 16
#define AP_WR_LAT_BUDGET6_MASK CM_BITMASK(23:16)
#define AP_WR_LAT_BUDGET7_LSB CM_BIT(24)
#define AP_WR_LAT_BUDGET7_SHIFT 24
#define AP_WR_LAT_BUDGET7_MASK CM_BITMASK(31:24)
/* EMI_THRO_LAT99 */
#define AP_WR_LAT_MARGIN0_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN0_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN0_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT100 */
#define AP_WR_LAT_MARGIN1_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN1_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN1_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT101 */
#define AP_WR_LAT_MARGIN2_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN2_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN2_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT102 */
#define AP_WR_LAT_MARGIN3_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN3_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN3_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT103 */
#define AP_WR_LAT_MARGIN4_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN4_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN4_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT104 */
#define AP_WR_LAT_MARGIN5_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN5_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN5_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT105 */
#define AP_WR_LAT_MARGIN6_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN6_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN6_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT106 */
#define AP_WR_LAT_MARGIN7_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_MARGIN7_2ND_SHIFT 0
#define AP_WR_LAT_MARGIN7_2ND_MASK CM_BITMASK(31:0)
/* EMI_THRO_LAT107 */
#define AP_WR_LAT_URGENT_THR0_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR0_2ND_SHIFT 0
#define AP_WR_LAT_URGENT_THR0_2ND_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR1_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR1_2ND_SHIFT 16
#define AP_WR_LAT_URGENT_THR1_2ND_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT108 */
#define AP_WR_LAT_URGENT_THR2_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR2_2ND_SHIFT 0
#define AP_WR_LAT_URGENT_THR2_2ND_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR3_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR3_2ND_SHIFT 16
#define AP_WR_LAT_URGENT_THR3_2ND_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT109 */
#define AP_WR_LAT_URGENT_THR4_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR4_2ND_SHIFT 0
#define AP_WR_LAT_URGENT_THR4_2ND_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR5_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR5_2ND_SHIFT 16
#define AP_WR_LAT_URGENT_THR5_2ND_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT110 */
#define AP_WR_LAT_URGENT_THR6_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_URGENT_THR6_2ND_SHIFT 0
#define AP_WR_LAT_URGENT_THR6_2ND_MASK CM_BITMASK(15:0)
#define AP_WR_LAT_URGENT_THR7_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_URGENT_THR7_2ND_SHIFT 16
#define AP_WR_LAT_URGENT_THR7_2ND_MASK CM_BITMASK(31:16)
/* EMI_THRO_LAT111 */
#define AP_WR_LAT_BUDGET0_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_BUDGET0_2ND_SHIFT 0
#define AP_WR_LAT_BUDGET0_2ND_MASK CM_BITMASK(7:0)
#define AP_WR_LAT_BUDGET1_2ND_LSB CM_BIT(8)
#define AP_WR_LAT_BUDGET1_2ND_SHIFT 8
#define AP_WR_LAT_BUDGET1_2ND_MASK CM_BITMASK(15:8)
#define AP_WR_LAT_BUDGET2_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_BUDGET2_2ND_SHIFT 16
#define AP_WR_LAT_BUDGET2_2ND_MASK CM_BITMASK(23:16)
#define AP_WR_LAT_BUDGET3_2ND_LSB CM_BIT(24)
#define AP_WR_LAT_BUDGET3_2ND_SHIFT 24
#define AP_WR_LAT_BUDGET3_2ND_MASK CM_BITMASK(31:24)
/* EMI_THRO_LAT112 */
#define AP_WR_LAT_BUDGET4_2ND_LSB CM_BIT(0)
#define AP_WR_LAT_BUDGET4_2ND_SHIFT 0
#define AP_WR_LAT_BUDGET4_2ND_MASK CM_BITMASK(7:0)
#define AP_WR_LAT_BUDGET5_2ND_LSB CM_BIT(8)
#define AP_WR_LAT_BUDGET5_2ND_SHIFT 8
#define AP_WR_LAT_BUDGET5_2ND_MASK CM_BITMASK(15:8)
#define AP_WR_LAT_BUDGET6_2ND_LSB CM_BIT(16)
#define AP_WR_LAT_BUDGET6_2ND_SHIFT 16
#define AP_WR_LAT_BUDGET6_2ND_MASK CM_BITMASK(23:16)
#define AP_WR_LAT_BUDGET7_2ND_LSB CM_BIT(24)
#define AP_WR_LAT_BUDGET7_2ND_SHIFT 24
#define AP_WR_LAT_BUDGET7_2ND_MASK CM_BITMASK(31:24)

#define cm_mgr_read(addr)	__raw_readl((void __force __iomem *)(addr))
#define cm_mgr_write(addr, val)	mt_reg_sync_writel(val, addr)

#endif /* __MTK_CM_MGR_PLATFORM_REG_H__*/
