#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/pmic

# Mediatek PMIC MT63XX specific files
obj-$(CONFIG_MTK_PMIC_CHIP_MT6336)          += mt6336.o mt6336_irq.o mt6336_common.o mt6336_efuse.o mt6336_auxadc.o
#obj-y          += mt6336.o mt6336_irq.o mt6336_common.o
