/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef __MT_CLK_ID_MT6797_H__
#define __MT_CLK_ID_MT6797_H__

/* The following is CODA name */
enum mt_cg_clk_id {

	MT_CG_INFRA0_MD2MD_CCIF_CG3_STA              =   0,
	MT_CG_INFRA0_SPI_CG_STA                      =   1,
	MT_CG_INFRA0_MSDC0_CG_STA                    =   2,
	MT_CG_INFRA0_MD2MD_CCIF_CG4_STA              =   3,
	MT_CG_INFRA0_MSDC1_CG_STA                    =   4,
	MT_CG_INFRA0_MSDC2_CG_STA                    =   5,
	MT_CG_INFRA0_MSDC3_CG_STA                    =   6,
	MT_CG_INFRA0_MD2MD_CCIF_CG5_STA              =   7,
	MT_CG_INFRA0_GCPU_CG_STA                     =   8,
	MT_CG_INFRA0_AUXADC_CG_STA                   =  10,
	MT_CG_INFRA0_CPUM_CG_STA                     =  11,
	MT_CG_INFRA0_AP_C2K_CCIF_0_CG_STA            =  12,
	MT_CG_INFRA0_AP_C2K_CCIF_1_CG_STA            =  13,
	MT_CG_INFRA0_CLDMA_CG_STA                    =  16,
	MT_CG_INFRA0_DISP_PWM_CG_STA                 =  17,
	MT_CG_INFRA0_AP_DMA_CG_STA                   =  18,
	MT_CG_INFRA0_MD1L1MCU_AP_BUS_CK_CG_STA       =  19,
	MT_CG_INFRA0_DEVICE_APC_CG_STA               =  20,
	MT_CG_INFRA0_MD1L1SYS_AP_BUS                 =  21,
	MT_CG_INFRA0_I2C_SRAM_CG_STA                 =  22,
	MT_CG_INFRA0_CCIF_AP_CG_STA                  =  23,
	MT_CG_INFRA0_DEBUGSYS_CG_STA                 =  24,
	MT_CG_INFRA0_AUDIO_CG_STA                    =  25,
	MT_CG_INFRA0_CCIF_MD_CG_STA                  =  26,
	MT_CG_INFRA0_MD1MCU_AP_BUS_CK_CG_STA         =  27,
	MT_CG_INFRA0_MD1BUS_AP_BUS_CK_CG_STA         =  28,
	MT_CG_INFRA0_MD1LTE_AP_BUS_CK_CG_STA         =  29,
	MT_CG_INFRA0_MD1DBG_AP_BUS_CK_CG_STA         =  30,
	MT_CG_INFRA0_DRAMC_F26M_CG_STA               =  31,

	MT_CG_INFRA1_PMIC_CG_TMR_STA                 =  32 +  0,
	MT_CG_INFRA1_PMIC_CG_AP_STA                  =  32 +  1,
	MT_CG_INFRA1_PMIC_CG_MD_STA                  =  32 +  2,
	MT_CG_INFRA1_PMIC_CG_CONN_STA                =  32 +  3,
	MT_CG_INFRA1_SCPSYS_CG_STA                   =  32 +  4,
	MT_CG_INFRA1_SEJ_CG_STA                      =  32 +  5,
	MT_CG_INFRA1_APXGPT_CG_STA                   =  32 +  6,
	MT_CG_INFRA1_SEJ_13M_CG_STA                  =  32 +  7,
	MT_CG_INFRA1_ICUSB_CG_STA                    =  32 +  8,
	MT_CG_INFRA1_GCE_CG_STA                      =  32 +  9,
	MT_CG_INFRA1_THERM_CG_STA                    =  32 + 10,
	MT_CG_INFRA1_I2C0_CG_STA                     =  32 + 11,
	MT_CG_INFRA1_I2C1_CG_STA                     =  32 + 12,
	MT_CG_INFRA1_I2C2_CG_STA                     =  32 + 13,
	MT_CG_INFRA1_I2C3_CG_STA                     =  32 + 14,
	MT_CG_INFRA1_PWM_HCLK_CG_STA                 =  32 + 15,
	MT_CG_INFRA1_PWM1_CG_STA                     =  32 + 16,
	MT_CG_INFRA1_PWM2_CG_STA                     =  32 + 17,
	MT_CG_INFRA1_PWM3_CG_STA                     =  32 + 18,
	MT_CG_INFRA1_PWM4_CG_STA                     =  32 + 19,
	MT_CG_INFRA1_PWM_CG_STA                      =  32 + 21,
	MT_CG_INFRA1_UART0_CG_STA                    =  32 + 22,
	MT_CG_INFRA1_UART1_CG_STA                    =  32 + 23,
	MT_CG_INFRA1_UART2_CG_STA                    =  32 + 24,
	MT_CG_INFRA1_UART3_CG_STA                    =  32 + 25,
	MT_CG_INFRA1_MD2MD_CCIF_CG0_STA              =  32 + 27,
	MT_CG_INFRA1_MD2MD_CCIF_CG1_STA              =  32 + 28,
	MT_CG_INFRA1_MD2MD_CCIF_CG2_STA              =  32 + 29,
	MT_CG_INFRA1_FHCTL_CG_STA                    =  32 + 30,
	MT_CG_INFRA1_BTIF_CG_STA                     =  32 + 31,


	MT_CG_INFRA2_I2C4_CG_STA                     =  64 +  0,
	MT_CG_INFRA2_I2C_APPM_CG_STA                 =  64 +  1,
	MT_CG_INFRA2_I2C_GPUPM_CG_STA                =  64 +  2,
	MT_CG_INFRA2_I2C2_IMM_CG_STA                 =  64 +  3,
	MT_CG_INFRA2_I2C2_ARB_CG_STA                 =  64 +  4,
	MT_CG_INFRA2_I2C3_IMM_CG_STA                 =  64 +  5,
	MT_CG_INFRA2_I2C3_ARB_CG_STA                 =  64 +  6,
	MT_CG_INFRA2_I2C5_CG_STA                     =  64 +  7,
	MT_CG_INFRA2_SYS_CIRQ_CG_STA                 =  64 +  8,
	MT_CG_INFRA2_SPI1_CG_STA                     =  64 + 10,
	MT_CG_INFRA2_DRAMC_B_F26M_CG_STA             =  64 + 11,
	MT_CG_INFRA2_ANC_MD32_CG_STA                 =  64 + 12,
	MT_CG_INFRA2_ANC_MD32_32K_CG_STA             =  64 + 13,
	MT_CG_INFRA2_DVFS_SPM0_CG_STA                =  64 + 14,
	MT_CG_INFRA2_DVFS_SPM1_CG_STA                =  64 + 15,
	MT_CG_INFRA2_AES_TOP0_CG_STA                 =  64 + 16,
	MT_CG_INFRA2_AES_TOP1_CG_STA                 =  64 + 17,
	MT_CG_INFRA2_SSUSB_BUS_CG_STA                =  64 + 18,
	MT_CG_INFRA2_SPI2_CG_STA                     =  64 + 19,
	MT_CG_INFRA2_SPI3_CG_STA                     =  64 + 20,
	MT_CG_INFRA2_SPI4_CG_STA                     =  64 + 21,
	MT_CG_INFRA2_SPI5_CG_STA                     =  64 + 22,
	MT_CG_INFRA2_IRTX_CG_STA                     =  64 + 23,
	MT_CG_INFRA2_SSUSB_SYS_CG_STA                =  64 + 24,
	MT_CG_INFRA2_SSUSB_REF_CG_STA                =  64 + 25,
	MT_CG_INFRA2_AUDIO_26M_CG_STA                =  64 + 26,
	MT_CG_INFRA2_AUDIO_26M_PAD_TOP_CG_STA        =  64 + 27,
	MT_CG_INFRA2_MODEM_TEMP_SHARE_CG_STA         =  64 + 28,
	MT_CG_INFRA2_VAD_WRAP_SOC_CG_STA             =  64 + 29,
	MT_CG_INFRA2_DRAMC_CONF_CG_STA               =  64 + 30,
	MT_CG_INFRA2_DRAMC_B_CONF_CG_STA             =  64 + 31,

	MT_CG_ID_DISP0_SMI_COMMON                    =  96 +  0,
	MT_CG_ID_DISP0_SMI_LARB0                     =  96 +  1,
	MT_CG_ID_DISP0_SMI_LARB5                     =  96 +  2,
	MT_CG_ID_DISP0_CAM_MDP                       =  96 +  3,
	MT_CG_ID_DISP0_MDP_RDMA0                     =  96 +  4,
	MT_CG_ID_DISP0_MDP_RDMA1                     =  96 +  5,
	MT_CG_ID_DISP0_MDP_RSZ0                      =  96 +  6,
	MT_CG_ID_DISP0_MDP_RSZ1                      =  96 +  7,
	MT_CG_ID_DISP0_MDP_RSZ2                      =  96 +  8,
	MT_CG_ID_DISP0_MDP_TDSHP                     =  96 +  9,
	MT_CG_ID_DISP0_MDP_COLOR                     =  96 + 10,
	MT_CG_ID_DISP0_MDP_WDMA                      =  96 + 11,
	MT_CG_ID_DISP0_MDP_WROT0                     =  96 + 12,
	MT_CG_ID_DISP0_MDP_WROT1                     =  96 + 13,
	MT_CG_ID_DISP0_FAKE_ENG                      =  96 + 14,
	MT_CG_ID_DISP0_DISP_OVL0                     =  96 + 15,
	MT_CG_ID_DISP0_DISP_OVL1                     =  96 + 16,
	MT_CG_ID_DISP0_DISP_2L_OVL0                  =  96 + 17,
	MT_CG_ID_DISP0_DISP_2L_OVL1                  =  96 + 18,
	MT_CG_ID_DISP0_DISP_RDMA0                    =  96 + 19,
	MT_CG_ID_DISP0_DISP_RDMA1                    =  96 + 20,
	MT_CG_ID_DISP0_DISP_WDMA0                    =  96 + 21,
	MT_CG_ID_DISP0_DISP_WDMA1                    =  96 + 22,
	MT_CG_ID_DISP0_DISP_COLOR                    =  96 + 23,
	MT_CG_ID_DISP0_DISP_CCORR                    =  96 + 24,
	MT_CG_ID_DISP0_DISP_AAL                      =  96 + 25,
	MT_CG_ID_DISP0_DISP_GAMMA                    =  96 + 26,
	MT_CG_ID_DISP0_DISP_OD                       =  96 + 27,
	MT_CG_ID_DISP0_DISP_DITHER                   =  96 + 28,
	MT_CG_ID_DISP0_DISP_UFOE_MOUT                =  96 + 29,
	MT_CG_ID_DISP0_DISP_DSC                      =  96 + 30,
	MT_CG_ID_DISP0_DISP_SPLIT                    =  96 + 31,

	MT_CG_ID_DISP1_DSI0_MM                       = 128 +  0,
	MT_CG_ID_DISP1_DSI0_INTERFACE                = 128 +  1,
	MT_CG_ID_DISP1_DSI1_MM                       = 128 +  2,
	MT_CG_ID_DISP1_DSI1_INTERFACE                = 128 +  3,
	MT_CG_ID_DISP1_DPI_MM                        = 128 +  4,
	MT_CG_ID_DISP1_DPI_INTERFACE                 = 128 +  5,
	MT_CG_ID_DISP1_LARB4_AXI_ASIF_MM             = 128 +  6,
	MT_CG_ID_DISP1_LARB4_AXI_ASIF_MJC            = 128 +  7,
	MT_CG_ID_DISP1_DISP_OVL0_MOUT                = 128 +  8,
	MT_CG_ID_DISP1_FAKE_ENG2                     = 128 +  9,

	MT_CG_IMAGE_ISP_PWR_RST_B                    = 160 +  0,
	MT_CG_IMAGE_ISP_PWR_ISO                      = 160 +  1,
	MT_CG_IMAGE_ISP_PWR_ON                       = 160 +  2,
	MT_CG_IMAGE_ISP_PWR_ON_2ND                   = 160 +  3,
	MT_CG_IMAGE_ISP_PWR_CLK_DIS                  = 160 +  4,
	MT_CG_IMAGE_ISP_SRAM_PDN0                    = 160 +  5,
	MT_CG_IMAGE_ISP_SRAM_PDN1                    = 160 +  6,
	MT_CG_IMAGE_ISP_SRAM_PDN2                    = 160 +  7,
	MT_CG_IMAGE_ISP_SRAM_PDN3                    = 160 +  8,

	MT_CG_MFG_PWR_RST_B                          = 192 +  0,
	MT_CG_MFG_PWR_ISO                            = 192 +  1,
	MT_CG_MFG_PWR_ON                             = 192 +  2,
	MT_CG_MFG_PWR_ON_2ND                         = 192 +  3,
	MT_CG_MFG_PWR_CLK_DIS                        = 192 +  4,

	MT_CG_ID_AUDIO_AFE                           = 224 +  2,      /* PDN_AFE         */
	MT_CG_ID_AUDIO_I2S                           = 224 +  6,      /* PDN_I2S         */
	MT_CG_ID_AUDIO_ADDA4_ADC                     = 224 +  7,
	MT_CG_ID_AUDIO_22M                           = 224 +  8,      /* PDN_22M         */
	MT_CG_ID_AUDIO_24M                           = 224 +  9,      /* PDN_24M         */
	MT_CG_ID_AUDIO_APB_W2T                       = 224 + 12,
	MT_CG_ID_AUDIO_APB_R2T                       = 224 + 13,
	MT_CG_ID_AUDIO_APB3_SEL                      = 224 + 14,
	MT_CG_ID_AUDIO_APLL2_TUNER                   = 224 + 18,      /* PDN_APLL2_TUNER */
	MT_CG_ID_AUDIO_APLL_TUNER                    = 224 + 19,      /* PDN_APLL_TUNER  */
	MT_CG_ID_AUDIO_PDN_TDM_CK                    = 224 + 20,
	MT_CG_ID_AUDIO_ADC                           = 224 + 24,
	MT_CG_ID_AUDIO_DAC                           = 224 + 25,
	MT_CG_ID_AUDIO_DAC_PREDIS                    = 224 + 26,
	MT_CG_ID_AUDIO_TML                           = 224 + 27,
	MT_CG_ID_AUDIO_AHB_IDLE_EN_EXT               = 224 + 29,
	MT_CG_ID_AUDIO_AHB_IDLE_EN_INT               = 224 + 30,

	MT_CG_VDE_PWR_RST_B                          = 256 +  0,
	MT_CG_VDE_PWR_ISO                            = 256 +  1,
	MT_CG_VDE_PWR_ON                             = 256 +  2,
	MT_CG_VDE_PWR_ON_2ND                         = 256 +  3,
	MT_CG_VDE_PWR_CLK_DIS                        = 256 +  4,
	MT_CG_VDE_SRAM_PDN0                          = 256 +  8,
	MT_CG_VDE_SRAM_PDN1                          = 256 +  9,
	MT_CG_VDE_SRAM_PDN2                          = 256 + 10,
	MT_CG_VDE_SRAM_PDN3                          = 256 + 11,

	MT_CG_VEN_PWR_RST_B                          = 288 +  0,
	MT_CG_VEN_PWR_ISO                            = 288 +  1,
	MT_CG_VEN_PWR_ON                             = 288 +  2,
	MT_CG_VEN_PWR_ON_2ND                         = 288 +  3,
	MT_CG_VEN_PWR_CLK_DIS                        = 288 +  4,
	MT_CG_VEN_SRAM_PDN0                          = 288 +  8,
	MT_CG_VEN_SRAM_PDN1                          = 288 +  9,
	MT_CG_VEN_SRAM_PDN2                          = 288 + 10,
	MT_CG_VEN_SRAM_PDN3                          = 288 + 11,

	MT_CG_MJC_PWR_RST_B                          = 320 +  0,
	MT_CG_MJC_PWR_ISO                            = 320 +  1,
	MT_CG_MJC_PWR_ON                             = 320 +  2,
	MT_CG_MJC_PWR_ON_2ND                         = 320 +  3,
	MT_CG_MJC_PWR_CLK_DIS                        = 320 +  4,
	MT_CG_MJC_SRAM_PDN0                          = 320 +  8,
	MT_CG_MJC_SRAM_PDN1                          = 320 +  9,
	MT_CG_MJC_SRAM_PDN2                          = 320 + 10,
	MT_CG_MJC_SRAM_PDN3                          = 320 + 11
};

#endif /* __MT_CLK_ID_MT6797_H__ */
