/****************************************************************
* Auto generated by DE, please DO NOT modify this file directly.
*****************************************************************/

#ifndef __MT_SPM_PMIC_WRAP__H__
#define __MT_SPM_PMIC_WRAP__H__

#if defined(CONFIG_ARCH_MT6755)

#include "mt_spm_pmic_wrap_mt6755.h"

#elif defined(CONFIG_ARCH_MT6797)

#include "mt_spm_pmic_wrap_mt6797.h"

#endif

#endif /* __MT_SPM_PMIC_WRAP__H__ */
