obj-$(CONFIG_SND_SOC_AW87XXX)+= snd-soc-aw87390.o
snd-soc-aw87390-objs += aw87xxx.o
snd-soc-aw87390-objs += aw87xxx_acf_bin.o
snd-soc-aw87390-objs += aw87xxx_bin_parse.o
snd-soc-aw87390-objs += aw87xxx_device.o
snd-soc-aw87390-objs += aw87xxx_dsp.o
snd-soc-aw87390-objs += aw87xxx_monitor.o
