#
# Makefile for the mediatek phy drivers.
#
ccflags-$(CONFIG_PHY_MTK_SOLUTION) := -I$(srctree)/drivers/misc/mediatek/mu3phy/
obj-$(CONFIG_PHY_MTK_SOLUTION)		+= phy-mtk.o
obj-$(CONFIG_PHY_MTK_SSUSB)		+= phy-mtk-ssusb.o
