ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m4u/$(MTK_PLATFORM)/

obj-y += smi_variant.o
obj-y += smi_debug.o
obj-y += smi_variant_config_8173.o
obj-y += smi_variant_config_8127.o
obj-y += smi_variant_config_8163.o
