# MTK Platform Support

obj-y += common/
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_audio_v3/
obj-$(CONFIG_MT_SND_SOC_6580) += mt_soc_audio_6580/
obj-$(CONFIG_MT_SND_SOC_6797) += mt_soc_audio_6797/
obj-$(CONFIG_MT_SND_SOC_6755) += mt_soc_audio_6755/
obj-$(CONFIG_SND_SOC_MT8173) += mt_soc_audio_8173/
obj-$(CONFIG_MT_SND_SOC_8163) += mt_soc_audio_8163/
ifneq ($(CONFIG_MT_SND_SOC_2701),)
obj-$(CONFIG_MT_SND_SOC_2701) += mt2701/
endif
