# MTK Platform Support

obj-y += common/
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_audio_v1/
obj-$(CONFIG_MT_SND_SOC_V2) += mt_soc_audio_v2/
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_audio_v3/
obj-$(CONFIG_MT_SND_SOC_6580) += mt_soc_audio_6580/
obj-$(CONFIG_MT_SND_SOC_8163) += mt_soc_audio_8163/
