#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# MTK Platform Support

obj-y += common/
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_audio_v3/
obj-$(CONFIG_MT_SND_SOC_6580) += mt_soc_audio_6580/
obj-$(CONFIG_MT_SND_SOC_6797) += mt_soc_audio_6797/
obj-$(CONFIG_MT_SND_SOC_6755) += mt_soc_audio_6755/
obj-$(CONFIG_MT_SND_SOC_6750) += mt_soc_audio_6750/
obj-$(CONFIG_SND_SOC_MT8173) += mt_soc_audio_8173/
obj-$(CONFIG_MT_SND_SOC_8163) += mt_soc_audio_8163/
obj-$(CONFIG_MT_SND_SOC_8127) += mt_soc_audio_8127/
ifneq ($(CONFIG_MT_SND_SOC_2701),)
obj-$(CONFIG_MT_SND_SOC_2701) += mt2701/
endif
