/*
* Copyright (C) 2016 MediaTek Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 as
* published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See http://www.gnu.org/licenses/gpl-2.0.html for more details.
*/

#ifndef __TINNO_CUSTOM_CHARGER_H__
#define __TINNO_CUSTOM_CHARGER_H__

#define CUSTOM_BATTERY_CV 4400000
#define CUSTOM_V_CHARGER_MAX 6500000				/* 6.5 V */

#define PRECHARGE_CURRENT					120000
#define TERMINATION_CURRENT					150000

#define CUSTOM_USB_CHARGER_CURRENT_SUSPEND			0		/* def CONFIG_USB_IF */
#define CUSTOM_USB_CHARGER_CURRENT_UNCONFIGURED		70000	/* 70mA */
#define CUSTOM_USB_CHARGER_CURRENT_CONFIGURED		500000	/* 500mA */
#define CUSTOM_USB_CHARGER_CURRENT					500000	/* 500mA */
#define CUSTOM_AC_CHARGER_CURRENT					950000
#define CUSTOM_AC_CHARGER_INPUT_CURRENT				1000000
#define CUSTOM_NON_STD_AC_CHARGER_CURRENT			500000
#define CUSTOM_CHARGING_HOST_CHARGER_CURRENT		650000
#define CUSTOM_APPLE_1_0A_CHARGER_CURRENT			650000
#define CUSTOM_APPLE_2_1A_CHARGER_CURRENT			800000
#define CUSTOM_TA_AC_CHARGING_CURRENT				3000000

/* sw jeita */
#define CUSTOM_ENABLE_JEITA 1
/*jeita current setting*/
#define CUSTOM_AC_45_TO_60_TEMP_CHARGER_CURRENT			950000 //temp 45~60 current
#define CUSTOM_AC_45_TO_60_TEMP_INPUT_CHARGER_CURRENT	1000000 //temp 45~60 input current
#define CUSTOM_AC_10_TO_45_TEMP_CHARGER_CURRENT			CUSTOM_AC_CHARGER_CURRENT  //temp 10~45 current
#define CUSTOM_AC_10_TO_45_TEMP_INPUT_CHARGER_CURRENT	CUSTOM_AC_CHARGER_INPUT_CURRENT  //temp 10~45 input current
#define CUSTOM_AC_0_TO_10_TEMP_CHARGER_CURRENT			550000 //temp 0~10 current
#define CUSTOM_AC_0_TO_10_TEMP_INPUT_CHARGER_CURRENT	550000 //temp 0~10 input current
#define CUSTOM_JEITA_TEMP_ABOVE_T4_CV_VOLTAGE	4100000 //temp > 60
#define CUSTOM_JEITA_TEMP_T3_TO_T4_CV_VOLTAGE	4100000 //temp 45~60
#define CUSTOM_JEITA_TEMP_T2_TO_T3_CV_VOLTAGE	4400000 //temp 15~45
#define CUSTOM_JEITA_TEMP_T1_TO_T2_CV_VOLTAGE	4400000 //temp 0~15
#define CUSTOM_JEITA_TEMP_T0_TO_T1_CV_VOLTAGE	4400000 //temp 0~0
#define CUSTOM_JEITA_TEMP_BELOW_T0_CV_VOLTAGE	4100000 //tem < 0
#define CUSTOM_TEMP_T4_THRESHOLD  57
#define CUSTOM_TEMP_T4_THRES_MINUS_X_DEGREE 54
#define CUSTOM_TEMP_T3_THRESHOLD  45
#define CUSTOM_TEMP_T3_THRES_MINUS_X_DEGREE 43
#define CUSTOM_TEMP_T2_THRESHOLD  15
#define CUSTOM_TEMP_T2_THRES_PLUS_X_DEGREE 17
#define CUSTOM_TEMP_T1_THRESHOLD  3
#define CUSTOM_TEMP_T1_THRES_PLUS_X_DEGREE 5
#define CUSTOM_TEMP_T0_THRESHOLD  -10
#define CUSTOM_TEMP_T0_THRES_PLUS_X_DEGREE  -6
#define CUSTOM_TEMP_NEG_10_THRESHOLD 0

/* Battery Temperature Protection */
#define CUSTOM_MIN_CHARGE_TEMPERATURE  3
#define CUSTOM_MIN_CHARGE_TEMPERATURE_PLUS_X_DEGREE	5
#define CUSTOM_MAX_CHARGE_TEMPERATURE  57
#define CUSTOM_MAX_CHARGE_TEMPERATURE_MINUS_X_DEGREE	54

/* pe */
#define CUSTOM_PE_ICHG_LEAVE_THRESHOLD 1000 /* mA */
#define CUSTOM_TA_AC_12V_INPUT_CURRENT 3200000
#define CUSTOM_TA_AC_9V_INPUT_CURRENT	3200000
#define CUSTOM_TA_AC_7V_INPUT_CURRENT	3200000
#define CUSTOM_TA_9V_SUPPORT
#define CUSTOM_TA_12V_SUPPORT

/* pe2.0 */
#define CUSTOM_PE20_ICHG_LEAVE_THRESHOLD 1000 /* mA */
#define CUSTOM_TA_START_BATTERY_SOC	0
#define CUSTOM_TA_STOP_BATTERY_SOC	85

/* dual charger */
#define CUSTOM_TA_AC_MASTER_CHARGING_CURRENT 1500000
#define CUSTOM_TA_AC_SLAVE_CHARGING_CURRENT 1500000


/* cable measurement impedance */
#define CUSTOM_CABLE_IMP_THRESHOLD 699
#define CUSTOM_VBAT_CABLE_IMP_THRESHOLD 3900

/* bif */
#define CUSTOM_BIF_THRESHOLD1 4250000	/* UV */
#define CUSTOM_BIF_THRESHOLD2 4300000	/* UV */
#define CUSTOM_BIF_CV_UNDER_THRESHOLD2 4450000	/* UV */
#define CUSTOM_BIF_CV BATTERY_CV /* UV */

#define CUSTOM_R_SENSE 68 /* mohm */

#define CUSTOM_MAX_CHARGING_TIME (12 * 60 * 60) /* 12 hours */

/* battery warning */
#define CUSTOM_BATTERY_NOTIFY_CASE_0001_VCHARGER
#define CUSTOM_BATTERY_NOTIFY_CASE_0002_VBATTEMP

/* TODO :need change to CONFIG_MTK_SWCHR_SUPPORT config */
/* #define SWCHR_POWER_PATH */

#endif /*__TINNO_CUSTOM_CHARGER_H__*/
