/*
 * Copyright (C) 2016 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include "vpu_reg.h"
#include "vpu_cmn.h"

static uint64_t vpu_base;

struct vpu_reg_desc g_vpu_reg_descs[VPU_NUM_REGS] = {
#define INS_REG(reg, offset, size) \
	{ REG_ ## reg, #reg, offset, size }

	INS_REG(RESET, 0x00, 4),
	INS_REG(EVENT_TRIG, 0x04, 4),
	INS_REG(INT_EN, 0x08, 4),
	INS_REG(DONE_ST, 0x0C, 4),
	INS_REG(CTRL, 0x10, 4),
	INS_REG(XTENSA_INT, 0x14, 4),
	INS_REG(CTL_XTENSA_INT, 0x18, 4),
	INS_REG(INT_MASK, 0x2C, 4),
	INS_REG(TOP_SPARE, 0x38, 4),
	INS_REG(AXI_DEFAULT0, 0x3C, 4),
	INS_REG(AXI_DEFAULT1, 0x40, 4),
	INS_REG(AXI_DEFAULT2, 0x44, 4),
	INS_REG(AXI_DEFAULT3, 0x48, 4),
	INS_REG(CABGEN_CTRL, 0x4C, 4),
	INS_REG(XTENSA_INFO00, 0x50, 4),
	INS_REG(XTENSA_INFO01, 0x54, 4),
	INS_REG(XTENSA_INFO02, 0x58, 4),
	INS_REG(XTENSA_INFO03, 0x5C, 4),
	INS_REG(XTENSA_INFO04, 0x60, 4),
	INS_REG(XTENSA_INFO05, 0x64, 4),
	INS_REG(XTENSA_INFO06, 0x68, 4),
	INS_REG(XTENSA_INFO07, 0x6C, 4),
	INS_REG(XTENSA_INFO08, 0x70, 4),
	INS_REG(XTENSA_INFO09, 0x74, 4),
	INS_REG(XTENSA_INFO10, 0x78, 4),
	INS_REG(XTENSA_INFO11, 0x7C, 4),
	INS_REG(XTENSA_INFO12, 0x80, 4),
	INS_REG(XTENSA_INFO13, 0x84, 4),
	INS_REG(XTENSA_INFO14, 0x88, 4),
	INS_REG(XTENSA_INFO15, 0x8C, 4),
	INS_REG(XTENSA_INFO16, 0x90, 4),
	INS_REG(XTENSA_INFO17, 0x94, 4),
	INS_REG(XTENSA_INFO18, 0x98, 4),
	INS_REG(XTENSA_INFO19, 0x9C, 4),
	INS_REG(XTENSA_INFO20, 0xA0, 4),
	INS_REG(XTENSA_INFO21, 0xA4, 4),
	INS_REG(XTENSA_INFO22, 0xA8, 4),
	INS_REG(XTENSA_INFO23, 0xAC, 4),
	INS_REG(XTENSA_INFO24, 0xB0, 4),
	INS_REG(XTENSA_INFO25, 0xB4, 4),
	INS_REG(XTENSA_INFO26, 0xB8, 4),
	INS_REG(XTENSA_INFO27, 0xBC, 4),
	INS_REG(XTENSA_INFO28, 0xC0, 4),
	INS_REG(XTENSA_INFO29, 0xC4, 4),
	INS_REG(XTENSA_INFO30, 0xC8, 4),
	INS_REG(XTENSA_INFO31, 0xCC, 4),
	INS_REG(DEBUG_INFO00, 0xD0, 4),
	INS_REG(DEBUG_INFO01, 0xD4, 4),
	INS_REG(DEBUG_INFO02, 0xD8, 4),
	INS_REG(DEBUG_INFO03, 0xDC, 4),
	INS_REG(DEBUG_INFO04, 0xE0, 4),
	INS_REG(DEBUG_INFO05, 0xE4, 4),
	INS_REG(DEBUG_INFO06, 0xE8, 4),
	INS_REG(DEBUG_INFO07, 0xEC, 4),
	INS_REG(DEBUG_INFO08, 0xF0, 4)
#undef INS_REG
};


struct vpu_reg_field_desc g_vpu_reg_field_descs[VPU_NUM_REG_FIELDS] = {
#define INS_FIELD(reg, field, msb, lsb) \
	{ REG_ ## reg, FLD_ ## field, #field, msb, lsb }

	INS_FIELD(RESET, SHARE_SRAM_CONFIG, 31, 30),
	INS_FIELD(RESET, DCACHE_SRAM_EN, 29, 29),
	INS_FIELD(RESET, APB_PADDR_REG, 28, 17),
	INS_FIELD(RESET, IPU_DM_RST, 16, 16),
	INS_FIELD(RESET, APB_MODE, 13, 13),
	INS_FIELD(RESET, IPU_OCD_HALT_ON_RST, 12, 12),
	INS_FIELD(RESET, IPU_D_RST, 8, 8),
	INS_FIELD(RESET, IPU_B_RST, 4, 4),
	INS_FIELD(RESET, IPU_HW_RST, 0, 0),
	INS_FIELD(EVENT_TRIG, GCE_EVENT3, 12, 12),
	INS_FIELD(EVENT_TRIG, GCE_EVENT2, 8, 8),
	INS_FIELD(EVENT_TRIG, GCE_EVENT1, 4, 4),
	INS_FIELD(EVENT_TRIG, GCE_EVENT0, 0, 0),
	INS_FIELD(INT_EN, IPU_INT_EN_RESERVED, 31, 0),
	INS_FIELD(DONE_ST, P_WAIT_MODE, 7, 7),
	INS_FIELD(DONE_ST, BREAK_IN_ACK, 6, 6),
	INS_FIELD(DONE_ST, BREAK_OUT, 5, 5),
	INS_FIELD(DONE_ST, XOCD_MODE, 4, 4),
	INS_FIELD(CTRL, P_DEBUG_ENABLE, 31, 31),
	INS_FIELD(CTRL, STROBE, 30, 30),
	INS_FIELD(CTRL, PARB_CLK_EN, 27, 27),
	INS_FIELD(CTRL, PBCLK_EN, 26, 26),
	INS_FIELD(CTRL, RUN_STALL, 23, 23),
	INS_FIELD(CTRL, TRIG_IN_IDMA, 22, 22),
	INS_FIELD(CTRL, BREAK_OUT_ACK, 21, 21),
	INS_FIELD(CTRL, BREAK_IN, 20, 20),
	INS_FIELD(CTRL, STAT_VECTOR_SEL, 19, 19),
	INS_FIELD(CTRL, TIE2APB_CLK_EN, 18, 18),
	INS_FIELD(CTRL, BUS_PIF_GATED, 17, 17),
	INS_FIELD(CTRL, PRID, 16, 1),
	INS_FIELD(CTRL, NMI, 0, 0),
	INS_FIELD(XTENSA_INT, INT_RSV_XTENSA, 31, 1),
	INS_FIELD(XTENSA_INT, INT_XTENSA, 0, 0),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA15, 15, 15),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA14, 14, 14),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA13, 13, 13),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA12, 12, 12),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA11, 11, 11),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA10, 10, 10),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA09, 9, 9),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA08, 8, 8),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA07, 7, 7),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA06, 6, 6),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA05, 5, 5),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA04, 4, 4),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA03, 3, 3),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA02, 2, 2),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA01, 1, 1),
	INS_FIELD(CTL_XTENSA_INT, INT_CTL_XTENSA00, 0, 0),
	INS_FIELD(INT_MASK, APMCU_INT_MASK, 16, 16),
	INS_FIELD(INT_MASK, CTL_XTENSA_INT_MASK, 15, 0),
	INS_FIELD(TOP_SPARE, IPU_SPARE, 31, 0),
	INS_FIELD(AXI_DEFAULT0, AR_USER_CORE_8_4, 29, 25),
	INS_FIELD(AXI_DEFAULT0, AW_USER_CORE_8_4, 24, 20),
	INS_FIELD(AXI_DEFAULT0, AR_USER_IDMA_8_4, 17, 13),
	INS_FIELD(AXI_DEFAULT0, AW_USER_IDMA_8_4, 12, 8),
	INS_FIELD(AXI_DEFAULT0, AR_DOMAIN_4_3, 7, 6),
	INS_FIELD(AXI_DEFAULT0, AW_DOMAIN_4_3, 5, 4),
	INS_FIELD(AXI_DEFAULT0, CACHE_S_ADDR_HPART, 3, 2),
	INS_FIELD(AXI_DEFAULT0, MM1_S_ADDR_HPART, 1, 0),
	INS_FIELD(AXI_DEFAULT1, AR_DOMAIN_APB, 30, 28),
	INS_FIELD(AXI_DEFAULT1, AR_FLUSH_APB, 27, 24),
	INS_FIELD(AXI_DEFAULT1, AW_DOMAIN_APB, 22, 20),
	INS_FIELD(AXI_DEFAULT1, AW_FLUSH_APB, 19, 16),
	INS_FIELD(AXI_DEFAULT1, AR_FLUSH_CORE, 15, 12),
	INS_FIELD(AXI_DEFAULT1, AW_FLUSH_CORE, 11, 8),
	INS_FIELD(AXI_DEFAULT1, AR_FLUSH_IDMA, 7, 4),
	INS_FIELD(AXI_DEFAULT1, AW_FLUSH_IDMA, 3, 0),
	INS_FIELD(AXI_DEFAULT2, AR_DOMAIN_CAM, 30, 28),
	INS_FIELD(AXI_DEFAULT2, AR_FLUSH_CAM, 27, 24),
	INS_FIELD(AXI_DEFAULT2, AW_DOMAIN_CAM, 22, 20),
	INS_FIELD(AXI_DEFAULT2, AW_FLUSH_CAM, 19, 16),
	INS_FIELD(AXI_DEFAULT2, AR_DOMAIN_IMG, 14, 12),
	INS_FIELD(AXI_DEFAULT2, AR_FLUSH_IMG, 11, 8),
	INS_FIELD(AXI_DEFAULT2, AW_DOMAIN_IMG, 6, 4),
	INS_FIELD(AXI_DEFAULT2, AW_FLUSH_IMG, 3, 0),
	INS_FIELD(AXI_DEFAULT3, AR_DOMAIN_CORE, 30, 28),
	INS_FIELD(AXI_DEFAULT3, AW_DOMAIN_CORE, 22, 20),
	INS_FIELD(AXI_DEFAULT3, SPNIDEN, 19, 19),
	INS_FIELD(AXI_DEFAULT3, SPIDEN, 18, 18),
	INS_FIELD(AXI_DEFAULT3, NIDEN, 17, 17),
	INS_FIELD(AXI_DEFAULT3, DBG_EN, 16, 16),
	INS_FIELD(AXI_DEFAULT3, AR_DOMAIN_IDMA, 14, 12),
	INS_FIELD(AXI_DEFAULT3, AW_DOMAIN_IDMA, 6, 4),
	INS_FIELD(AXI_DEFAULT3, AR_PROT_1_CORE, 3, 3),
	INS_FIELD(AXI_DEFAULT3, AW_PROT_1_CORE, 2, 2),
	INS_FIELD(AXI_DEFAULT3, AR_PROT_1_IDMA, 1, 1),
	INS_FIELD(AXI_DEFAULT3, AW_PROT_1_IDMA, 0, 0),
	INS_FIELD(CABGEN_CTRL, M_1_OUTSTAND_EXTEND_ON, 15, 15),
	INS_FIELD(CABGEN_CTRL, M_1_QOS_ON, 14, 14),
	INS_FIELD(CABGEN_CTRL, M_0_OUTSTAND_EXTEND_ON, 13, 13),
	INS_FIELD(CABGEN_CTRL, M_0_QOS_ON, 12, 12),
	INS_FIELD(CABGEN_CTRL, SI_1_WAY_INTERLEAVE_EN, 11, 10),
	INS_FIELD(CABGEN_CTRL, SI_1_OUTSTAND_DISABLE, 9, 9),
	INS_FIELD(CABGEN_CTRL, SI_1_CTRL_BYPASS, 8, 8),
	INS_FIELD(CABGEN_CTRL, SI_1_WAY_EN, 7, 6),
	INS_FIELD(CABGEN_CTRL, SI_0_WAY_INTERLEAVE_EN, 5, 4),
	INS_FIELD(CABGEN_CTRL, SI_0_OUTSTAND_DISABLE, 3, 3),
	INS_FIELD(CABGEN_CTRL, SI_0_CTRL_BYPASS, 2, 2),
	INS_FIELD(CABGEN_CTRL, SI_0_WAY_EN, 1, 0),
	INS_FIELD(XTENSA_INFO00, XTENSA_INFO0, 31, 0),
	INS_FIELD(XTENSA_INFO01, XTENSA_INFO1, 31, 0),
	INS_FIELD(XTENSA_INFO02, XTENSA_INFO2, 31, 0),
	INS_FIELD(XTENSA_INFO03, XTENSA_INFO3, 31, 0),
	INS_FIELD(XTENSA_INFO04, XTENSA_INFO4, 31, 0),
	INS_FIELD(XTENSA_INFO05, XTENSA_INFO5, 31, 0),
	INS_FIELD(XTENSA_INFO06, XTENSA_INFO6, 31, 0),
	INS_FIELD(XTENSA_INFO07, XTENSA_INFO7, 31, 0),
	INS_FIELD(XTENSA_INFO08, XTENSA_INFO8, 31, 0),
	INS_FIELD(XTENSA_INFO09, XTENSA_INFO9, 31, 0),
	INS_FIELD(XTENSA_INFO10, XTENSA_INFO10, 31, 0),
	INS_FIELD(XTENSA_INFO11, XTENSA_INFO11, 31, 0),
	INS_FIELD(XTENSA_INFO12, XTENSA_INFO12, 31, 0),
	INS_FIELD(XTENSA_INFO13, XTENSA_INFO13, 31, 0),
	INS_FIELD(XTENSA_INFO14, XTENSA_INFO14, 31, 0),
	INS_FIELD(XTENSA_INFO15, XTENSA_INFO15, 31, 0),
	INS_FIELD(XTENSA_INFO16, XTENSA_INFO16, 31, 0),
	INS_FIELD(XTENSA_INFO17, XTENSA_INFO17, 31, 0),
	INS_FIELD(XTENSA_INFO18, XTENSA_INFO18, 31, 0),
	INS_FIELD(XTENSA_INFO19, XTENSA_INFO19, 31, 0),
	INS_FIELD(XTENSA_INFO20, XTENSA_INFO20, 31, 0),
	INS_FIELD(XTENSA_INFO21, XTENSA_INFO21, 31, 0),
	INS_FIELD(XTENSA_INFO22, XTENSA_INFO22, 31, 0),
	INS_FIELD(XTENSA_INFO23, XTENSA_INFO23, 31, 0),
	INS_FIELD(XTENSA_INFO24, XTENSA_INFO24, 31, 0),
	INS_FIELD(XTENSA_INFO25, XTENSA_INFO25, 31, 0),
	INS_FIELD(XTENSA_INFO26, XTENSA_INFO26, 31, 0),
	INS_FIELD(XTENSA_INFO27, XTENSA_INFO27, 31, 0),
	INS_FIELD(XTENSA_INFO28, XTENSA_INFO28, 31, 0),
	INS_FIELD(XTENSA_INFO29, XTENSA_INFO29, 31, 0),
	INS_FIELD(XTENSA_INFO30, XTENSA_INFO30, 31, 0),
	INS_FIELD(XTENSA_INFO31, XTENSA_INFO31, 31, 0),
	INS_FIELD(DEBUG_INFO00, IPU_DBG_INFO00, 31, 0),
	INS_FIELD(DEBUG_INFO01, IPU_DBG_INFO01_RESERVED, 31, 24),
	INS_FIELD(DEBUG_INFO01, IPU_DBG_INFO01, 23, 0),
	INS_FIELD(DEBUG_INFO02, IPU_DBG_INFO02, 31, 0),
	INS_FIELD(DEBUG_INFO03, IPU_DBG_INFO03, 31, 0),
	INS_FIELD(DEBUG_INFO04, IPU_DBG_INFO04, 31, 0),
	INS_FIELD(DEBUG_INFO05, IPU_DBG_INFO05, 31, 0),
	INS_FIELD(DEBUG_INFO06, IPU_DBG_INFO06_RESERVED, 31, 24),
	INS_FIELD(DEBUG_INFO06, IPU_DBG_INFO06, 23, 0),
	INS_FIELD(DEBUG_INFO07, IPU_DBG_INFO07, 31, 0),
	INS_FIELD(DEBUG_INFO08, IPU_DBG_INFO08, 31, 0)
#undef INS_FIELD
};


int vpu_init_reg(struct vpu_device *device)
{
	vpu_base = device->vpu_base;
	return 0;
}

uint32_t vpu_read_field(enum vpu_reg_field f)
{
	struct vpu_reg_desc *reg;
	struct vpu_reg_field_desc *field;
	uint32_t reg_val;
	uint8_t msb, lsb;

	field = &g_vpu_reg_field_descs[f];
	reg = &g_vpu_reg_descs[field->reg];
	reg_val = vpu_read_reg32(vpu_base, reg->offset);
	msb = field->msb;
	lsb = field->lsb;

	if (msb - lsb > 30)
		return reg_val;
	return (reg_val & (((1L << (msb - lsb + 1)) - 1) << lsb)) >> lsb;
}


void vpu_write_field(enum vpu_reg_field f, uint32_t v)
{
	struct vpu_reg_desc *reg;
	struct vpu_reg_field_desc *field;
	uint8_t msb, lsb;
	uint32_t temp;

	field = &g_vpu_reg_field_descs[f];
	reg = &g_vpu_reg_descs[field->reg];
	msb = field->msb;
	lsb = field->lsb;

	temp = F_REG(vpu_base, reg->offset);
	temp &= ~F_MSK(msb, lsb);
	temp |= F_VAL(v, msb, lsb);
	F_REG(vpu_base, reg->offset) = temp;
}
