obj-$(CONFIG_MICROTRUST_KEYMASTER_DRIVER) += mt_keymaster.o
#obj-$(CONFIG_NEU_TZ_DRIVER) += mt_keymaster_service.o
#EXTRA_CFLAGS += -D DEBUG_DO -fno-pic 
ccflags-y += -D DEBUG_DO
ccflags-y += -Wno-error
