obj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o
obj-$(CONFIG_MTK_SCPSYS_MT8173) += mtk-scpsys.o
obj-$(CONFIG_MTK_SCPSYS_MT8163) += mtk-scpsys-mt8163.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_SCPSYS_MT2701) += mtk-scpsys-mt2701.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_SCPSYS_MT8127) += mtk-scpsys-mt8127.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_PMIC_WRAP_COMMON) += mtk-pmic-wrap.o
