obj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o
obj-$(CONFIG_MTK_SCPSYS_MT8173) += mtk-scpsys.o
obj-$(CONFIG_MTK_SCPSYS_MT8163) += mtk-scpsys-mt8163.o
obj-$(CONFIG_MTK_SCPSYS_MT2701) += mtk-scpsys-mt2701.o
