ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/

obj-$(CONFIG_MTK_DRAMC) := mt_dramc.o
ccflags-$(CONFIG_MTK_DRAMC) += -DDEBUG
