# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
        $(subdrv-rpath)/mot_naples_s5kkdsmipiraw_Sensor.o
        #(subdrv-rpath)/mot_s5kkdsqt_eeprom.o \

