# Makefile for Linux samples code
obj-$(CONFIG_TINNO_TP_ILITEK)   += ILITEK_V2/
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi/
obj-$(CONFIG_TOUCHSCREEN_MTK_ILITEK) += ili9881x_tddi/
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_NOVA_HOSTDL) += NVT_Touch/
# ANT DETECT
obj-$(CONFIG_TINNO_ANT_DET)   += ant_det/
obj-y   += lcm/
# product device info
obj-$(CONFIG_TINNO_PRODUCT_INFO)    += dev_info/
obj-y   += smartpa/aw87xxx/

obj-y += tpd_control.o \
		tpd_button.o \
		tpd_debug.o \
		tpd_default.o \
		tpd_misc.o \
		tpd_setting.o

