# Makefile for Linux samples code
obj-y   += touch/
obj-y   += lcm/
obj-y   += sensors/
obj-y   += charger/

# product device info
obj-$(CONFIG_TINNO_PRODUCT_INFO)    += dev_info/

# fingerprint.
obj-y                               += fingerprint/
obj-y   += smartpa/fs1818/
obj-y   += smartpa/fs1894/

