#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y	+=  tgesture.o
