###
# Copyright (C) 2018 Fourier Semiconductor Inc. All rights reserved.
#

EXTRA_CFLAGS += -Wall -Werror

snd-soc-fsm-objs := fsm_core.o
snd-soc-fsm-objs += fs1603.o
snd-soc-fsm-objs += fsm_i2c.o

obj-$(CONFIG_SND_SOC_FS16XX) += snd-soc-fsm.o
