# drivers/image/jpeg/Makefile

ccflags-y = -DSDEBUG_T

#obj-$(CONFIG_MTK_JPEG) += jpeg_driver.o
obj-y += jpeg_driver.o

jpeg_driver-objs := jpeg_drv_6589_enc.o jpeg_drv_6589_dec.o jpeg_drv.o

#jpeg_driver-objs := jpeg_drv_6589_enc.o  jpeg_drv.o

# EOF
