#include $(srctree)/drivers/misc/mediatek/Makefile.custom

IMGSENSOR_SUBDRV_OBJ := \
    $(subdrv-rpath)/mot_maui_hi1634bmipiraw_Sensor.o

obj-$(CONFIG_MTK_IMGSENSOR_ISP4_C) += $(IMGSENSOR_SUBDRV_OBJ)
