/*****************************************************************************
 *
 * Filename:
 * ---------
 *   devinfo_emi.h
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *   This Module defines the EMI (external memory interface) related setting.
 *
 * Author:
 * -------
 *  EMI auto generator V0.01
 *
 *   Memory Device database last modified on 2016/10/21
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * WARNING!!!  WARNING!!!   WARNING!!!  WARNING!!!  WARNING!!!  WARNING!!! 
 * This file is generated by EMI Auto-gen Tool.
 * Please do not modify the content directly!
 * It could be overwritten!
 *============================================================================
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/


#ifndef DEVINFO_EMI_H
#define DEVINFO_EMI_H

/******************************************************************
This file is auto generated by emigen.pl,and follows "emi.h"
Pls remake or new preloader to generate!
By shaohui mods 20121217
******************************************************************/
/******************************************************************
Update by :shaohui
Date	: 20160103
To	:
update Discreate info 
******************************************************************/
/******************************************************************
Update by :shaohui
Date	: 20161102
To	:
Re-update Discreate info 
******************************************************************/


/*shaohui add to indicate dis ddr setting,20160103*/
//#define DEVINFO_DIS_DDR_STATUS 

typedef struct
{
    int   sub_version;            // sub_version: 0x1 for new version
    int  type;                /* 0x0000 : Invalid
                                 0x0001 : Discrete DDR1
                                 0x0002 : Discrete LPDDR2
                                 0x0003 : Discrete LPDDR3
                                 0x0004 : Discrete PCDDR3
                                 0x0101 : MCP(NAND+DDR1)
                                 0x0102 : MCP(NAND+LPDDR2)
                                 0x0103 : MCP(NAND+LPDDR3)
                                 0x0104 : MCP(NAND+PCDDR3)
                                 0x0201 : MCP(eMMC+DDR1)
                                 0x0202 : MCP(eMMC+LPDDR2)
                                 0x0203 : MCP(eMMC+LPDDR3)
                                 0x0204 : MCP(eMMC+PCDDR3)
                              */
    int   id_length;              // EMMC and NAND ID checking length
    int   fw_id_length;              // FW ID checking length
    char  ID[16];
    char  fw_id[8];               // To save fw id
    int   EMI_CONA_VAL;           //x3000
    int   DRAMC_DRVCTL0_VAL;      //x40B8               -> customized TX I/O driving
    int   DRAMC_DRVCTL1_VAL;      //x40BC               -> customized TX I/O driving
    int   DRAMC_ACTIM_VAL;        //x4000
    int   DRAMC_GDDR3CTL1_VAL;    //x40F4
    int   DRAMC_CONF1_VAL;        //x4004
    int   DRAMC_DDR2CTL_VAL;      //x407C 
    int   DRAMC_TEST2_3_VAL;      //x4044
    int   DRAMC_CONF2_VAL;        //x4008
    int   DRAMC_PD_CTRL_VAL;      //x41DC
    int   DRAMC_PADCTL3_VAL;      //x4014               -> customized TX DQS delay
    int   DRAMC_DQODLY_VAL;       //x4200~0x420C        -> customized TX DQ delay
    int   DRAMC_ADDR_OUTPUT_DLY;  // for E1 DDR2 only
    int   DRAMC_CLK_OUTPUT_DLY;   // for E1 DDR2 only
    int   DRAMC_ACTIM1_VAL;       //x41E8
    int   DRAMC_MISCTL0_VAL;      //x40FC
    int   DRAMC_ACTIM05T_VAL;     //x41F8
    int   DRAM_RANK_SIZE[4];
    int   reserved[10];

    union
    {
        struct
        {
            int   LPDDR2_MODE_REG_1;
            int   LPDDR2_MODE_REG_2;
            int   LPDDR2_MODE_REG_3;
            int   LPDDR2_MODE_REG_5;
            int   LPDDR2_MODE_REG_10;
            int   LPDDR2_MODE_REG_63;
        };
        struct
        {
            int   DDR1_MODE_REG;
            int   DDR1_EXT_MODE_REG;
        };
        struct
        {
            int   PCDDR3_MODE_REG0;
            int   PCDDR3_MODE_REG1;
            int   PCDDR3_MODE_REG2;
            int   PCDDR3_MODE_REG3;
            int   PCDDR3_MODE_REG4;
            int   PCDDR3_MODE_REG5;
        };
        struct
        {
            int   LPDDR3_MODE_REG_1;
            int   LPDDR3_MODE_REG_2;
            int   LPDDR3_MODE_REG_3;
            int   LPDDR3_MODE_REG_5;
            int   LPDDR3_MODE_REG_10;
            int   LPDDR3_MODE_REG_63;
        };
    };
} EMI_SETTINGS;



extern int num_of_emi_records;
extern EMI_SETTINGS emi_settings[];

/* 0: invalid */
/* 1: mDDR1 */
/* 2: mDDR2 */
/* 3: mDDR3 */
#endif

