ccflags-y := -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/mmc/host/mediatek/$(PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lct_meminfo

obj-y += devinfo_emi.o
obj-y += devinfo_flash.o
