ccflags-y += -I$(srctree)/drivers/misc/mediatek/power_gs/$(MTK_PLATFORM)/

obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_ARCH_MT6735) += mt_power_gs-v1.o
obj-$(CONFIG_ARCH_MT6735M) += mt_power_gs-v1.o
obj-$(CONFIG_ARCH_MT6753) += mt_power_gs-v1.o
obj-$(CONFIG_ARCH_MT6580) += mt_power_gs-v1.o
obj-$(CONFIG_ARCH_MT6755) += mt_power_gs-v1.o
obj-$(CONFIG_ARCH_MT6797) += mt_power_gs-v1.o
