#
# Makefile for all kinds of Fingerprint
#
#obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
#obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
#obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MICROTRUST_FP_FOCALTECH)   += focaltech/
obj-$(CONFIG_MICROTRUST_FP_FPSENSOR)    += fpsensor_tee/
