#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_LCT_FPS_ET320) += lct_et320/
## tee_xuzhifeng@wind-mobi.com 20161117 begin
obj-$(CONFIG_EGISTEC_FINGERPRINT)  += egistec/
## tee_xuzhifeng@wind-mobi.com 20161117 end
