#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_LCT_FPS_ET320) += lct_et320/

# finally these two components should be unified
obj-$(CONFIG_EGISTEC_FINGERPRINT)  += egistec/
obj-$(CONFIG_LCT_FPC_TEE_EGIS) += egistec/

