
# Linux driver folder

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include/


#obj-y	+=  lib/
obj-y   +=  Config_FT6X36.o
obj-y   +=  DetailThreshold.o
obj-y   +=  Global.o
obj-y   +=  ini.o
obj-y   +=  Test_FT6X36.o
obj-y   +=  test_lib.o
obj-y   +=  focaltech_openshort_test.o	
obj-y	+=  focaltech_ctl.o
obj-y	+=  focaltech_ex_fun.o
obj-y	+=  focaltech_flash.o
obj-y	+=  focaltech_Gesture.o
obj-y	+=  focaltech_core.o
obj-y	+=  focaltech_esd_protection.o




