#
# Copyright (C) 2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_ARCH_MT6735) += lhd/
obj-$(CONFIG_ARCH_MT6735M) += lhd/
obj-$(CONFIG_ARCH_MT6753) += lhd/
#obj-$(CONFIG_ARCH_MT6580) += lhd/
obj-$(CONFIG_ARCH_MT6755) += ppm/
obj-$(CONFIG_ARCH_MT6797) += ppm/
