# sipa driver
snd-soc-sipa-objs := sipa.o
snd-soc-sipa-objs += sipa_regmap.o
snd-soc-sipa-objs += sipa_aux_dev_if.o
snd-soc-sipa-objs += sipa_91xx.o
snd-soc-sipa-objs += sipa_parameter.o
obj-$(CONFIG_SND_SOC_SIPA) += snd-soc-sipa.o

#sipa tuning
snd-soc-sipa-tuning-objs := sipa_tuning_misc.o
snd-soc-sipa-tuning-objs += sipa_tuning_if.o
obj-$(CONFIG_SND_SOC_SIPA) += snd-soc-sipa-tuning.o
