#
# Makefile for misc devices that really don't fit anywhere else.
#

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-y += ontim_ili9882n_hdplus_dsi_vdo_hlt.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
