ccflags-y += -I$(srctree)/drivers/misc/mediatek/rgbw/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/cm36652-new
obj-$(CONFIG_MTK_CM36652_NEW) := cm36652.o

