
# Mediatek PMIC MT63XX specific files
obj-$(CONFIG_MTK_PMIC_NEW_ARCH)          += pmic.o regulator_codegen.o pmic_regulator.o pmic_irq.o upmu_common.o pmic_auxadc.o pmic_chr_type_det.o pmic_initial_setting.o pmic_efuse.o
