#ifndef _FP_CONFIG_H
#define _FP_CONFIG_H

#define FASTPATH_RX_RESERVE (32)
#define FASTPATH_MAJOR  (230)
#define FASTPATH_MINOR  (0)
#define FASTPATH_SKBLIST
#define FASTPATH_NO_KERNEL_SUPPORT
#define FASTPATH_DISABLE_TCP_WINDOW_CHECK
#define FASTPATH_NETFILTER

#define XFRM_SKB_CB_EXT_OFFSET 108
#define XFRM_SKB_CB_DST_OFFSET 104

#define MD_DIRECT_TETHERING_RULE_NUM 128	/* Must be power of 2 */

#endif
