#ifndef _IOCTL_H
#define _IOCTL_H
#include <linux/ioctl.h>

#define FASTPATH_IOCTL_MAGIC    'W'
#define FASTPATH_IOCTL_RESET    _IO(FASTPATH_IOCTL_MAGIC, 0)
#define FASTPATH_IOCTL_ADDBR	_IO(FASTPATH_IOCTL_MAGIC, 1)
#define FASTPATH_IOCTL_DELBR	_IO(FASTPATH_IOCTL_MAGIC, 2)

#endif
