obj-y += mt_dcm.o
ifeq ($(CONFIG_MTK_LEGACY),y)
obj-y += mt_clkmgr_common_legacy.o
obj-y += mt_clkmgr_legacy.o
else
obj-y += mt_clkmgr_common.o
obj-y += mt_clkmgr.o
endif
obj-y += mt_spm_mtcmos.o
obj-y += mt_pbm.o
obj-y += mt_vcore_dvfs_1.o

