#zhangchao@wind-mobi.com add at 20170914 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += ili9881_hd720_dsi_vdo_yashi.o

#zhangchao@wind-mobi.com add at 20170914 end