ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-y	+=  bma2xx_offset_cali.o
obj-y	+=  bma2x2.o
#tuwenzan@wind-mobi.com modify at 20161108 end
