# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/include

obj-$(CONFIG_ABOV_SAR) += abov_sar.o
obj-$(CONFIG_ABOV_A96T346) += abov_a96t346df.o
