#
# Makefile for misc devices that really don't fit anywhere else.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/laser/stmvl53l0/inc

obj-y += vl53l0_api_ranging.o vl53l0_api_histogram.o vl53l0_api_calibration.o vl53l0_api_core.o vl53l0_api_strings.o vl53l0_api.o vl53l010_api.o vl53l010_tuning.o vl53l0_i2c_platform.o vl53l0_platform.o vl53l0_platform_log.o vl53l0_port_i2c.o

obj-y += stmvl53l0.o
