#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/ \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/leakage_table_v2/ \

obj-$(CONFIG_MACH_MT6759) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6759) += mtk_static_power_mt6759.o
