obj-y += \
    vdec_drv_vp9.o \
    vdec_drv_vp9_if.o \
    vdec_drv_vp9_utility.o \
    vdec_drv_vp9_vpu.o

ccflags-y += \
    -I$(srctree)/include/ \
    -I$(srctree)/drivers/media/platform/mediatek \
    -I$(srctree)/drivers/media/platform/mediatek/include \
    -I$(srctree)/drivers/media/platform/mediatek/vp9_dec

#ccflags-y += -DY_C_SEPARATE
#ccflags-y += -DVDEC_UFO_SUPPORT
