#MTK port custom Kbuild
#To Add 1.environment variable
include $(src)/Kbuild-mtk-custom-env

#Enable MFG Power Monitor
ccflags-y += -DENABLE_MFG_PERF

#Enable VCore DVFS Control
#Workaround for MT6757 HW issue,
#Limit VCore DVFS bottom is LPM mode for gaming performance
ifeq ($(CONFIG_MTK_PLATFORM), "mt6757")
#ccflags-y += -DENABLE_VCORE_DVFS_CONTROL
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/dramc/$(MTK_PLATFORM)/
endif

#Switch AXI1To2 Setting
#IT will detect DRAM type to decide to go M6+M7 or M6 only
ccflags-y += -DENABLE_AXI_1TO2_CONTROL

curr := platform/mt6757
obj-y += $(curr)/mtk_config_platform.o
