#
# Copyright (C) 2019 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += mot_coful_s5kjn1_qtech.o
#obj-y += mot_coful_s5kjn1_qtech_pdaf.o
#obj-y += mot_coful_s5kjn1_qtech_otp_cal.o // It is for old platform just in case.
