#liujinzhou@wind-mobi.com add at 20161128 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += hx8394f_hd720_dsi_vdo_boe.o

#liujinzhou@wind-mobi.com add at 20161128 end