ccflags-y += -Isound/soc/codecs/cs35l41/include
snd-soc-cs35l41-objs := sound/cs35l41-i2c.o sound/cs35l41.o sound/cs35l41-tables.o  sound/wm_adsp.o
obj-$(CONFIG_SND_SOC_CS35L41)			+= snd-soc-cs35l41.o

