#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += hx8394c_wxga_dsi_vdo.o lcm_drv_hx8394c_wxga_dsi_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

