/*
 * Copyright (C) 2016 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 */

#ifndef __MTK_CLK_ID_MT6799_H__
#define __MTK_CLK_ID_MT6799_H__

/* The following is CODA name */
enum mt_cg_clk_id {
	/* INFRA0 */
	MTK_CG_INFRA0_MD2MD_CCIF_MD_CG_STA_3                                      =   0,
	MTK_CG_INFRA0_MD2MD_CCIF_MD_CG_STA_4                                      =   3,
	MTK_CG_INFRA0_AUDIO_DCM_EN_STA                                            =   5,
	MTK_CG_INFRA0_CLDMA_AO_TOP_HCLK_CK_CG_STA                                 =   6,
	MTK_CG_INFRA0_MD2MD_CCIF_MD_CG_STA_5                                      =   7,
	MTK_CG_INFRA0_TRNG_CG_STA                                                 =   9,
	MTK_CG_INFRA0_AUXADC_CG_STA                                               =  10,
	MTK_CG_INFRA0_CPUM_CG_STA                                                 =  11,
	MTK_CG_INFRA0_CCIF1_AP_CG_STA                                             =  12,
	MTK_CG_INFRA0_CCIF1_MD_CG_STA                                             =  13,
	MTK_CG_INFRA0_CCIF2_AP_CG_STA                                             =  16,
	MTK_CG_INFRA0_CCIF2_MD_CG_STA                                             =  17,
	MTK_CG_INFRA0_XIU_CKCG_STA_FOR_DBG_CTRLER                                 =  19,
	MTK_CG_INFRA0_DEVICE_APC_CG_STA                                           =  20,
	MTK_CG_INFRA0_SMI_L2C_CK_CG_STA                                           =  22,
	MTK_CG_INFRA0_CCIF0_AP_CG_STA                                             =  23,
	MTK_CG_INFRA0_AUDIO_CG_STA                                                =  25,
	MTK_CG_INFRA0_CCIF0_MD_CG_STA                                             =  26,
	MTK_CG_INFRA0_RESERVED_FOR_EMI_L2C_FT_CK_CG_STA                           =  27,
	MTK_CG_INFRA0_RESERVED_FOR_SPM_PCM_CK_STA                                 =  28,
	MTK_CG_INFRA0_EMI_L2C_FT_CK_CG_STA_AND_ANC_MD32_CK_AND_SPM_PCM_CK         =  29,
	MTK_CG_INFRA0_ANC_MD32_CG_STA                                             =  30,
	MTK_CG_INFRA0_DRAMC_F26M_CK_STA                                           =  31,

	/* INFRA1 */
	MTK_CG_INFRA1_PMIC_CG_TMR_STA                                             =  32 +  0,
	MTK_CG_INFRA1_PMIC_CG_AP_STA                                              =  32 +  1,
	MTK_CG_INFRA1_PMIC_CG_MD_STA                                              =  32 +  2,
	MTK_CG_INFRA1_PMIC_CG_CONN_STA                                            =  32 +  3,
	MTK_CG_INFRA1_SCP_CG_STA                                                  =  32 +  4,
	MTK_CG_INFRA1_SEJ_CG_STA                                                  =  32 +  5,
	MTK_CG_INFRA1_APXGPT_CG_STA                                               =  32 +  6,
	MTK_CG_INFRA1_DVFSRC_CG_STA                                               =  32 +  7,
	MTK_CG_INFRA1_GCE_CG_STA                                                  =  32 +  8,
	MTK_CG_INFRA1_DBG_BCLK_CK_CG_STA                                          =  32 +  9,
	MTK_CG_INFRA1_SSHUB_APB_ASYNC_CG_STA                                      =  32 + 10,
	MTK_CG_INFRA1_RESERVED                                                    =  32 + 11,
	MTK_CG_INFRA1_SPM_APB_ASYNC_CG_STA                                        =  32 + 12,
	MTK_CG_INFRA1_CLDMA_AP_TOP_CG_STA                                         =  32 + 13,
	MTK_CG_INFRA1_CCIF3_AP_CG_STA                                             =  32 + 17,
	MTK_CG_INFRA1_AES_TOP0_CG_STA                                             =  32 + 18,
	MTK_CG_INFRA1_AES_TOP1_CG_STA                                             =  32 + 19,
	MTK_CG_INFRA1_DEVAPC_MPU_CG_STA                                           =  32 + 20,
	MTK_CG_INFRA1_RESERVED_FOR_CCIF4_AP_CG_STA                                =  32 + 21,
	MTK_CG_INFRA1_RESERVED_FOR_CCIF4_MD_CG_STA                                =  32 + 22,
	MTK_CG_INFRA1_CCIF3_MD_CG_STA                                             =  32 + 24,
	MTK_CG_INFRA1_RESERVED_FOR_CCIF5_AP_CG_STA                                =  32 + 25,
	MTK_CG_INFRA1_RESERVED_FOR_CCIF5_MD_CG_STA                                =  32 + 26,
	MTK_CG_INFRA1_MD2MD_CCIF_CG_STA_0                                         =  32 + 27,
	MTK_CG_INFRA1_MD2MD_CCIF_CG_STA_1_AND_MODEM_TEMP_SHARE_CG_STA             =  32 + 28,
	MTK_CG_INFRA1_MD2MD_CCIF_CG_STA_2                                         =  32 + 29,
	MTK_CG_INFRA1_FHCTL_CG_STA                                                =  32 + 30,
	MTK_CG_INFRA1_RESERVED_FOR_MODEM_TEMP_SHARE_CG_STA                        =  32 + 31,

	/* INFRA2 */
	MTK_CG_INFRA2_THERM_BCLK_CG_STA                                           =  64 +  6,
	MTK_CG_INFRA2_PTP_BCLK_CG_STA                                             =  64 +  7,
	MTK_CG_INFRA2_AUXADC_MD_CG_STA                                            =  64 + 24,
	MTK_CG_INFRA2_RESERVED                                                    =  64 + 29,
	MTK_CG_INFRA2_DVFS_CTRL_APB_RX_CK_CG_STA                                  =  64 + 30,

	/* PERI0 */
	MTK_CG_PERI0_RG_PWM_BCLK_CK_PDN_STA                                       =  96 +  0,
	MTK_CG_PERI0_RG_PWM_FBCLK1_CK_PDN_STA                                     =  96 +  1,
	MTK_CG_PERI0_RG_PWM_FBCLK2_CK_PDN_STA                                     =  96 +  2,
	MTK_CG_PERI0_RG_PWM_FBCLK3_CK_PDN_STA                                     =  96 +  3,
	MTK_CG_PERI0_RG_PWM_FBCLK4_CK_PDN_STA                                     =  96 +  4,
	MTK_CG_PERI0_RG_PWM_FBCLK5_CK_PDN_STA                                     =  96 +  5,
	MTK_CG_PERI0_RG_PWM_FBCLK6_CK_PDN_STA                                     =  96 +  6,
	MTK_CG_PERI0_RG_PWM_FBCLK7_CK_PDN_STA                                     =  96 +  7,
	MTK_CG_PERI0_RG_I2C0_BCLK_CK_PDN_STA                                      =  96 + 16,
	MTK_CG_PERI0_RG_I2C1_BCLK_CK_PDN_STA                                      =  96 + 17,
	MTK_CG_PERI0_RG_I2C2_BCLK_CK_PDN_STA                                      =  96 + 18,
	MTK_CG_PERI0_RG_I2C3_BCLK_CK_PDN_STA                                      =  96 + 19,
	MTK_CG_PERI0_RG_I2C4_BCLK_CK_PDN_STA                                      =  96 + 20,
	MTK_CG_PERI0_RG_I2C5_BCLK_CK_PDN_STA                                      =  96 + 21,
	MTK_CG_PERI0_RG_I2C6_BCLK_CK_PDN_STA                                      =  96 + 22,
	MTK_CG_PERI0_RG_I2C7_BCLK_CK_PDN_STA                                      =  96 + 23,
	MTK_CG_PERI0_RG_I2C8_BCLK_CK_PDN_STA                                      =  96 + 24,
	MTK_CG_PERI0_RG_I2C9_BCLK_CK_PDN_STA                                      =  96 + 25,

	/* PERI1 */
	MTK_CG_PERI1_RG_UART0_CK_PDN_STA                                         = 128 +  0,
	MTK_CG_PERI1_RG_UART1_CK_PDN_STA                                         = 128 +  1,
	MTK_CG_PERI1_RG_UART2_CK_PDN_STA                                         = 128 +  2,
	MTK_CG_PERI1_RG_UART3_CK_PDN_STA                                         = 128 +  3,
	MTK_CG_PERI1_RG_UART4_CK_PDN_STA                                         = 128 +  4,
	MTK_CG_PERI1_RG_UART5_CK_PDN_STA                                         = 128 +  5,
	MTK_CG_PERI1_RG_UART6_CK_PDN_STA                                         = 128 +  6,
	MTK_CG_PERI1_RG_UART7_CK_PDN_STA                                         = 128 +  7,
	MTK_CG_PERI1_RG_SPI0_CK_PDN_STA                                          = 128 + 16,
	MTK_CG_PERI1_RG_SPI1_CK_PDN_STA                                          = 128 + 17,
	MTK_CG_PERI1_RG_SPI2_CK_PDN_STA                                          = 128 + 18,
	MTK_CG_PERI1_RG_SPI3_CK_PDN_STA                                          = 128 + 19,
	MTK_CG_PERI1_RG_SPI4_CK_PDN_STA                                          = 128 + 20,
	MTK_CG_PERI1_RG_SPI5_CK_PDN_STA                                          = 128 + 21,
	MTK_CG_PERI1_RG_SPI6_CK_PDN_STA                                          = 128 + 22,
	MTK_CG_PERI1_RG_SPI7_CK_PDN_STA                                          = 128 + 23,
	MTK_CG_PERI1_RG_SPI8_CK_PDN_STA                                          = 128 + 24,
	MTK_CG_PERI1_RG_SPI9_CK_PDN_STA                                          = 128 + 25,
	MTK_CG_PERI1_RG_SPI10_CK_PDN_STA                                         = 128 + 26,

	/* PERI2 */
	MTK_CG_PERI2_RG_MSDC0_CK_PDN_AP_NORM_STA                                 = 160 +  0,
	MTK_CG_PERI2_RG_MSDC1_CK_PDN_STA                                         = 160 +  1,
	MTK_CG_PERI2_RG_MSDC3_CK_PDN_STA                                         = 160 +  3,
	MTK_CG_PERI2_RG_UFSCARD_CK_PDN_STA                                       = 160 + 10,
	MTK_CG_PERI2_RG_UFSCARD_MP_SAP_CFG_CK_PDN_STA                            = 160 + 11,
	MTK_CG_PERI2_RG_UFS_AES_CORE_CK_PDN_STA                                  = 160 + 12,
	MTK_CG_PERI2_RG_FLASHIF_CK_PDN_STA                                       = 160 + 16,
	MTK_CG_PERI2_RG_MSDC0_CK_PDN_AP_SECURE_STA                               = 160 + 24,
	MTK_CG_PERI2_RG_MSDC0_CK_PDN_MD_SECURE_STA                               = 160 + 25,
	MTK_CG_PERI2_RG_MSDC0_SRC_CK_PDN_AP_NORM_STA                             = 160 + 26,
	MTK_CG_PERI2_RG_MSDC1_SRC_CK_PDN_STA                                     = 160 + 27,
	MTK_CG_PERI2_RG_MSDC3_SRC_CK_PDN_STA                                     = 160 + 29,

	/* PERI3 */
	MTK_CG_PERI3_RG_USB_P0_CK_PDN_STA                                        = 192 +  0,
	MTK_CG_PERI3_RG_USB_P1_CK_PDN_STA                                        = 192 +  1,
	MTK_CG_PERI3_RG_MPCIE_P0_CK_PDN_STA                                      = 192 +  4,
	MTK_CG_PERI3_RG_MPCIE_P0_OBFF_CLK_CK_PDN_STA                             = 192 +  5,
	MTK_CG_PERI3_RG_MPCIE_P0_AUX_CLK_CK_PDN_STA                              = 192 +  6,

	/* PERI4 */
	MTK_CG_PERI4_RG_AP_DM_CK_PDN_STA                                         = 224 +  0,
	MTK_CG_PERI4_RG_IRTX_CK_PDN_STA                                          = 224 +  1,
	MTK_CG_PERI4_RG_DISP_PWM0_CK_PDN_STA                                     = 224 +  3,
	MTK_CG_PERI4_RG_DISP_PWM1_CK_PDN_STA                                     = 224 +  4,
	MTK_CG_PERI4_RG_BTIF_CK_PDN_STA                                          = 224 +  5,
	MTK_CG_PERI4_RG_CQ_DMA_CK_PDN_STA                                        = 224 +  6,
	MTK_CG_PERI4_RG_MBIST_MEM_OFF_DLY_CK_PDN_STA                             = 224 +  8,
	MTK_CG_PERI4_RG_DEVICE_APC_PERI_CK_PDN_STA                               = 224 +  9,
	MTK_CG_PERI4_RG_GCPU_CK_PDN_STA                                          = 224 + 10,
	MTK_CG_PERI4_RG_DXCC_AO_CK_PDN_STA                                       = 224 + 16,
	MTK_CG_PERI4_RG_DXCC_PUB_CK_PDN_STA                                      = 224 + 17,
	MTK_CG_PERI4_RG_DXCC_SEC_CK_PDN_STA                                      = 224 + 18,
	MTK_CG_PERI4_RG_DEBUGTOP_CK_PDN                                          = 224 + 20,
	MTK_CG_PERI4_RG_DXFDE_CORE_CK_PDN                                        = 224 + 24,
	MTK_CG_PERI4_RG_UFOZIP_CK_PDN_STA                                        = 224 + 28,

	/* PERI5 */
	MTK_CG_PERI5_RG_PERIAPB_PERICFG_REG_CK_PDN_STA                           = 256 +  0,
	MTK_CG_PERI5_RG_PERIAPB_SMI_4X1_INST_CK_PDN_STA                          = 256 +  1,
	MTK_CG_PERI5_RG_PERIAPB_POWER_METER_CK_PDN_STA                           = 256 +  2,
	MTK_CG_PERI5_RG_PERIAPB_VAD_CK_PDN_STA                                   = 256 +  3,

	/* AUDIO0 */
	MTK_CG_AUDIO0_PDN_AFE                                                    = 288 +  2,
	MTK_CG_AUDIO0_PDN_I2S                                                    = 288 +  6,
	MTK_CG_AUDIO0_PDN_22M                                                    = 288 +  8,
	MTK_CG_AUDIO0_PDN_24M                                                    = 288 +  9,
	MTK_CG_AUDIO0_APB_W2T                                                    = 288 + 12,
	MTK_CG_AUDIO0_APB_R2T                                                    = 288 + 13,
	MTK_CG_AUDIO0_APB3_SEL                                                   = 288 + 14,
	MTK_CG_AUDIO0_PDN_APLL2_TUNER                                            = 288 + 18,
	MTK_CG_AUDIO0_PDN_APLL_TUNER                                             = 288 + 19,
	MTK_CG_AUDIO0_PDN_TDM_CK                                                 = 288 + 20,
	MTK_CG_AUDIO0_PDN_ADC                                                    = 288 + 24,
	MTK_CG_AUDIO0_PDN_DAC                                                    = 288 + 25,
	MTK_CG_AUDIO0_PDN_DAC_PREDIS                                             = 288 + 26,
	MTK_CG_AUDIO0_PDN_TML                                                    = 288 + 27,
	MTK_CG_AUDIO0_AHB_IDLE_EN_EXT                                            = 288 + 29,
	MTK_CG_AUDIO0_AHB_IDLE_EN_INT                                            = 288 + 30,
	MTK_CG_AUDIO0_RESERVED                                                   = 288 + 31,

	/* AUDIO1 */
	MTK_CG_AUDIO1_I2S_SOFT_RST                                               = 320 +  1,
	MTK_CG_AUDIO1_I2S_SOFT_RST2                                              = 320 +  2,
	MTK_CG_AUDIO1_I2S1_BCLK_SW_CG                                            = 320 +  4,
	MTK_CG_AUDIO1_I2S2_BCLK_SW_CG                                            = 320 +  5,
	MTK_CG_AUDIO1_I2S3_BCLK_SW_CG                                            = 320 +  6,
	MTK_CG_AUDIO1_I2S4_BCLK_SW_CG                                            = 320 +  7,
	MTK_CG_AUDIO1_PDN_ADC_HIRES                                              = 320 + 16,
	MTK_CG_AUDIO1_PDN_ADC_HIRES_TML                                          = 320 + 17,
	MTK_CG_AUDIO1_PDN_ADDA6_ADC                                              = 320 + 20,
	MTK_CG_AUDIO1_PDN_ADDA6_ADC_HIRES                                        = 320 + 21,
	MTK_CG_AUDIO1_PDN_ADDA4_ADC                                              = 320 + 24,
	MTK_CG_AUDIO1_PDN_ADDA4_ADC_HIRES                                        = 320 + 25,
	MTK_CG_AUDIO1_PDN_ADDA5_ADC                                              = 320 + 26,
	MTK_CG_AUDIO1_PDN_ADDA5_ADC_HIRES                                        = 320 + 27,

	/* DISP0 */
	MTK_CG_DISP0_CG0_B0                                                      = 352 +  0,
	MTK_CG_DISP0_CG0_B1                                                      = 352 +  1,
	MTK_CG_DISP0_CG0_B2                                                      = 352 +  2,
	MTK_CG_DISP0_CG0_B3                                                      = 352 +  3,
	MTK_CG_DISP0_CG0_B4                                                      = 352 +  4,
	MTK_CG_DISP0_CG0_B5                                                      = 352 +  5,
	MTK_CG_DISP0_CG0_B6                                                      = 352 +  6,
	MTK_CG_DISP0_CG0_B7                                                      = 352 +  7,
	MTK_CG_DISP0_CG0_B8                                                      = 352 +  8,
	MTK_CG_DISP0_CG0_B9                                                      = 352 +  9,
	MTK_CG_DISP0_CG0_B10                                                     = 352 + 10,
	MTK_CG_DISP0_CG0_B11                                                     = 352 + 11,
	MTK_CG_DISP0_CG0_B12                                                     = 352 + 12,
	MTK_CG_DISP0_CG0_B13                                                     = 352 + 13,
	MTK_CG_DISP0_CG0_B14                                                     = 352 + 14,
	MTK_CG_DISP0_CG0_B15                                                     = 352 + 15,
	MTK_CG_DISP0_CG0_B16                                                     = 352 + 16,
	MTK_CG_DISP0_CG0_B17                                                     = 352 + 17,
	MTK_CG_DISP0_CG0_B18                                                     = 352 + 18,
	MTK_CG_DISP0_CG0_B19                                                     = 352 + 19,
	MTK_CG_DISP0_CG0_B20                                                     = 352 + 20,
	MTK_CG_DISP0_CG0_B21                                                     = 352 + 21,
	MTK_CG_DISP0_CG0_B22                                                     = 352 + 22,
	MTK_CG_DISP0_CG0_B23                                                     = 352 + 23,
	MTK_CG_DISP0_CG0_B24                                                     = 352 + 24,
	MTK_CG_DISP0_CG0_B25                                                     = 352 + 25,
	MTK_CG_DISP0_CG0_B26                                                     = 352 + 26,
	MTK_CG_DISP0_CG0_B27                                                     = 352 + 27,
	MTK_CG_DISP0_CG0_B28                                                     = 352 + 28,
	MTK_CG_DISP0_CG0_B29                                                     = 352 + 29,
	MTK_CG_DISP0_CG0_B30                                                     = 352 + 30,
	MTK_CG_DISP0_CG0_B31                                                     = 352 + 31,

	/* DISP1 */
	MTK_CG_DISP1_CG1_B0                                                      = 384 +  0,
	MTK_CG_DISP1_CG1_B1                                                      = 384 +  1,
	MTK_CG_DISP1_CG1_B2                                                      = 384 +  2,
	MTK_CG_DISP1_CG1_B3                                                      = 384 +  3,
	MTK_CG_DISP1_CG1_B4                                                      = 384 +  4,
	MTK_CG_DISP1_CG1_B5                                                      = 384 +  5,
	MTK_CG_DISP1_CG1_B6                                                      = 384 +  6,
	MTK_CG_DISP1_CG1_B7                                                      = 384 +  7,
	MTK_CG_DISP1_CG1_B8                                                      = 384 +  8,
	MTK_CG_DISP1_CG1_B9                                                      = 384 +  9,
	MTK_CG_DISP1_CG1_B10                                                     = 384 + 10,
	MTK_CG_DISP1_CG1_B11                                                     = 384 + 11,
	MTK_CG_DISP1_CG1_B12                                                     = 384 + 12,
	MTK_CG_DISP1_CG1_B13                                                     = 384 + 13,
	MTK_CG_DISP1_CG1_B14                                                     = 384 + 14,
	MTK_CG_DISP1_CG1_B15                                                     = 384 + 15,
	MTK_CG_DISP1_CG1_B16                                                     = 384 + 16,
	MTK_CG_DISP1_CG1_B17                                                     = 384 + 17,
	MTK_CG_DISP1_CG1_B18                                                     = 384 + 18,

	/* DISP2 */
	MTK_CG_DISP2_CG2_B0                                                      = 416 +  0,
	MTK_CG_DISP2_CG2_B1                                                      = 416 +  1,
	MTK_CG_DISP2_CG2_B2                                                      = 416 +  2,
	MTK_CG_DISP2_CG2_B3                                                      = 416 +  3,
	MTK_CG_DISP2_CG2_B4                                                      = 416 +  4,
	MTK_CG_DISP2_CG2_B5                                                      = 416 +  5,
	MTK_CG_DISP2_CG2_B6                                                      = 416 +  6,
	MTK_CG_DISP2_CG2_B7                                                      = 416 +  7,
	MTK_CG_DISP2_CG2_B8                                                      = 416 +  8,
	MTK_CG_DISP2_CG2_B9                                                      = 416 +  9,
	MTK_CG_DISP2_CG2_B10                                                     = 416 + 10,
	MTK_CG_DISP2_CG2_B11                                                     = 416 + 11,
	MTK_CG_DISP2_CG2_B12                                                     = 416 + 12,
	MTK_CG_DISP2_CG2_B13                                                     = 416 + 13,
	MTK_CG_DISP2_CG2_B14                                                     = 416 + 14,
	MTK_CG_DISP2_CG2_B15                                                     = 416 + 15,

	/* CAM */
	MTK_CG_CAM_LARB6_CGPDN                                                   = 448 +  0,
	MTK_CG_CAM_DFP_VAD_CGPDN                                                 = 448 +  1,
	MTK_CG_CAM_LARB3_CGPDN                                                   = 448 +  2,
	MTK_CG_CAM_RESERVED0                                                     = 448 +  3,
	MTK_CG_CAM_CAM_CGPDN                                                     = 448 +  6,
	MTK_CG_CAM_CAMTG_CGPDN                                                   = 448 +  7,
	MTK_CG_CAM_SENINF_CGPDN                                                  = 448 +  8,
	MTK_CG_CAM_CAMSV0_CGPDN                                                  = 448 +  9,
	MTK_CG_CAM_CAMSV1_CGPDN                                                  = 448 + 10,
	MTK_CG_CAM_CAMSV2_CGPDN                                                  = 448 + 11,
	MTK_CG_CAM_CCU_CGPDN                                                     = 448 + 12,

	/* IMAGE */
	MTK_CG_IMAGE_LARB5_CGPDN                                                 = 480 +  0,
	MTK_CG_IMAGE_LARB2_CGPDN                                                 = 480 +  1,
	MTK_CG_IMAGE_DIP_CGPDN                                                   = 480 +  2,
	MTK_CG_IMAGE_FDVT_CGPDN                                                  = 480 +  3,
	MTK_CG_IMAGE_DPE_CGPDN                                                   = 480 +  4,
	MTK_CG_IMAGE_RSC_CGPDN                                                   = 480 +  5,
	MTK_CG_IMAGE_WPE_CGPDN                                                   = 480 +  6,
	MTK_CG_IMAGE_GEPF_CGPDN                                                  = 480 +  7,
	MTK_CG_IMAGE_EAF_CGPDN                                                   = 480 +  8,
	MTK_CG_IMAGE_DFP_CGPDN                                                   = 480 + 10,
	MTK_CG_IMAGE_VAD_CGPDN                                                   = 480 + 11,

	/* MFG */
	MTK_CG_MFG_BAXI_PDN                                                      = 512 +  0,
	MTK_CG_MFG_BMEM_PDN                                                      = 512 +  1,
	MTK_CG_MFG_BG3D_PDN                                                      = 512 +  2,
	MTK_CG_MFG_B26M_PDN                                                      = 512 +  3,
	MTK_CG_MFG_KLX_SYSCLK_GATED_EN                                           = 512 +  4,
	MTK_CG_MFG_KLX_MEMCLK_GATED_EN                                           = 512 +  5,
	MTK_CG_MFG_KLX_CORECLK_GATED_EN                                          = 512 +  6,

	/* VDEC0 */
	MTK_CG_VDEC0_VDEC_CKEN                                                   = 544 +  0,
	MTK_CG_VDEC0_VDEC_ACTIVE                                                 = 544 +  4,
	MTK_CG_VDEC0_VDEC_CKEN_ENG                                               = 544 +  8,

	/* VDEC1 */
	LARB1_CKEN                                                               = 576 +  0,

	/* VENC0 */
	MTK_CG_VENC0_CE                                                          = 608 +  0,

	/* VENC1 */
	MTK_CG_VENC1_CKE0                                                        = 640 +  0,
	MTK_CG_VENC1_CKE1                                                        = 640 +  4,
	MTK_CG_VENC1_CKE2                                                        = 640 +  8,
	MTK_CG_VENC1_CKE3                                                        = 640 + 12,
	MTK_CG_VENC1_CKE4                                                        = 640 + 16,
	MTK_CG_VENC1_CKE5                                                        = 640 + 20,
	MTK_CG_VENC1_GALS_DCM_OFF                                                = 640 + 24,

	/* MJC */
	MTK_CG_MJC_SMI_LARB                                                      = 672 +  0,
	MTK_CG_MJC_MJC_TOP_CLOCK_GROUP_0                                         = 672 +  1,
	MTK_CG_MJC_MJC_TOP_CLOCK_GROUP_1                                         = 672 +  2,
	MTK_CG_MJC_MJC_TOP_CLOCK_GROUP_2                                         = 672 +  3,
	MTK_CG_MJC_MJC_FAKE_ENGINE                                               = 672 +  4,
	MTK_CG_MJC_RESERVED                                                      = 672 +  5,
	MTK_CG_MJC_METER                                                         = 672 +  6,

	/* IPU */
	MTK_CG_IPU_IPU_CGPDN                                                     = 704 +  0,
	MTK_CG_IPU_ISP_CGPDN                                                     = 704 +  1,
	MTK_CG_IPU_DFP_CGPDN                                                     = 704 +  2,
	MTK_CG_IPU_VAD_CGPDN                                                     = 704 +  3,
	MTK_CG_IPU_JTAG_CGPDN                                                    = 704 +  4,
	MTK_CG_IPU_INFRA_AXI_CGPDN                                               = 704 +  5,
	MTK_CG_IPU_INFRA_AHB_CGPDN                                               = 704 +  6,
	MTK_CG_IPU_MM_AXI_CGPDN                                                  = 704 +  7,
	MTK_CG_IPU_CAM_AXI_CGPDN                                                 = 704 +  8,
	MTK_CG_IPU_IMG_AXI_CGPDN                                                 = 704 +  9,
};

#endif /* __MTK_CLK_ID_MT6799_H__ */

