# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.
imgsensor_isp6s-objs += \
        $(subdrv-rpath)/mot_nevada_ov02bmipiraw_Sensor.o\
        $(subdrv-rpath)/eeprom_i2c_ov02b_driver.o \
