ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/ft5446/
ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/ft5446/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5446/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-y	+=  focaltech_core.o
obj-y	+=  focaltech_ctl.o
obj-y	+=  focaltech_ex_fun.o
obj-y	+=  focaltech_flash.o
obj-y	+=  focaltech_Gesture.o ./ft_gesture_lib.a

