#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.
imgsensor_isp6s-objs += \
	$(subdrv-rpath)/mot_bogota_gc32e1mipi_Sensor.o \
	# $(subdrv-rpath)/gc32e1_eeprom.o
