include $(srctree)/drivers/misc/mediatek/Makefile.custom


ifeq ($(CONFIG_MTK_MULTIBRIDGE_SUPPORT),y)
obj-y   +=  mt8193_ckgen.o
obj-y   +=  mt8193_ckgen_vfy.o
obj-y   +=  mt8193_gpio.o
obj-y   +=  mt8193_iic.o
obj-y   +=  mt8193_pinmux.o
endif