#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += hx8392a_dsi_vdo_2lane.o lcm_drv_hx8392a_dsi_vdo_2lane.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
