ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp
obj-$(CONFIG_AW9610X_SAR)  += aw9610x_mod.o
aw9610x_mod-objs := aw9610x_bin_parse.o aw9610x.o sar_factory.o
