#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += cpt_clap070wp03xg_sn65dsi83.o sn65dsi83_i2c.o lcm_drv_cpt_clap070wp03xg_sn65dsi83.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc