# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.
imgsensor_isp6s-objs += $(subdrv-rpath)/mot_taipei_s5k4h7mipiraw_Sensor.o
imgsensor_isp6s-objs += $(subdrv-rpath)/mot_taipei_s5k4h7mipiraw_otp.o
