#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += r69429_wqxga_dsi_vdo.o lcm_drv_r69429_wqxga_dsi_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
