#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_MACH_MT6757) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_KIBOPLUS) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6799) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6759) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6759) += udi_v1/
obj-$(CONFIG_MACH_MT6759) += ocp_v1/
obj-$(CONFIG_MACH_MT6799) += leakage_table_v1/
obj-$(CONFIG_MACH_MT6799) += cpufreq_v1/
obj-$(CONFIG_MACH_MT6799) += eem_v1/
obj-$(CONFIG_MACH_MT6799) += upower_v1/
obj-$(CONFIG_MACH_MT6757) += pbm_v1/
obj-$(CONFIG_MACH_KIBOPLUS) += pbm_v1/
obj-$(CONFIG_MACH_MT6799) += pbm_v2/
obj-$(CONFIG_MACH_MT6759) += pbm_v2/
obj-$(CONFIG_MACH_MT6757) += spm_v2/
obj-$(CONFIG_MACH_MT6757) += vcorefs_v1/
obj-$(CONFIG_MACH_MT6799) += vcorefs_v3/
obj-$(CONFIG_MACH_MT6799) += etc_v1/
obj-$(CONFIG_MACH_KIBOPLUS) += vcorefs_v1/
obj-$(CONFIG_MACH_KIBOPLUS) += spm_v2/
obj-$(CONFIG_MACH_MT6757) += cpuidle_v2/
obj-$(CONFIG_MACH_MT6799) += cpuidle_v2/
ifneq ($(CONFIG_FPGA_EARLY_PORTING),y)
obj-$(CONFIG_MACH_MT6757) += power_gs_v1/
obj-$(CONFIG_MACH_MT6799) += power_gs_v1/
obj-$(CONFIG_MACH_MT6759) += power_gs_v1/
endif
obj-$(CONFIG_MACH_MT6757) += hps_v2/
obj-$(CONFIG_MACH_MT6799) += hps_v3/
obj-$(CONFIG_MACH_KIBOPLUS) += hps_v2/
obj-$(CONFIG_MACH_MT6757) += ppm_v2/
obj-$(CONFIG_MACH_KIBOPLUS) += ppm_v2/
obj-$(CONFIG_MACH_MT6759) += ppm_v2/
obj-$(CONFIG_MACH_MT6799) += ppm_v2/
obj-$(CONFIG_MACH_MT6759) += spm_v3/
obj-$(CONFIG_MACH_MT6799) += spm_v3/
obj-$(CONFIG_MACH_MT6759) += clkbuf_v1/
obj-$(CONFIG_MACH_MT6799) += clkbuf_v1/
obj-$(CONFIG_MACH_MT6799) += dcm_v1/
obj-$(CONFIG_MACH_MT8167) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT8167) += hps_v1/
