subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/common
obj-$(CONFIG_SND_SOC_FS1815) += snd-soc-fs1815.o
snd-soc-fs1815-objs += fsm_core.o
snd-soc-fs1815-objs += fs1815.o
snd-soc-fs1815-objs += fsm_i2c.o
