ifeq ($(CONFIG_MTK_BMI120_NEW),y)

ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6735/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter
obj-y	:=  bmi160_stc.o

endif

