ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/mot
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/cm4
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp
obj-y	:=  moto_lts.o
