#include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/misc/mediatek/hdmi/inc

obj-y	+= slimport_drv.o slimport.o slimport_tx_drv.o slimport_platform.o

ccflags-y += 	-DCONFIG_SLIMPORT_ANX7808