#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += cpt_clap070wp03xg_lvds.o lcm_drv_cpt_clap070wp03xg_lvds.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
