# In case the platform does NOT support this type of sensors

obj-$(CONFIG_MTK_SCP_SENSORHUB) += SCP_sensorHub/
obj-$(CONFIG_MTK_SENSOR_HUB_SUPPORT) += SCP_shf/
obj-$(CONFIG_MTK_SCP_SENSORHUB_V1) += SCP_sensorHub_v1/
