#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_MTK_V4L2_LENS)   += media/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718/
obj-$(CONFIG_MTK_V4L2_LENS)   += lc898229/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9764/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9772a/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9772b/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7377a/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800w/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7375c/
obj-$(CONFIG_MTK_V4L2_LENS)   += bu64253gwz/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800v/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9768/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_dubai_dw9800v/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_dubai_ak7377a/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_aion_gt9764/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_aion_dw9800v/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_aion_gt9772/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_manaus_dw9800v/
obj-$(CONFIG_MTK_V4L2_LENS)   += mot_manaus_gt9764/
