#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifneq (, $(findstring limal, $(TARGET_PRODUCT)))
obj-y += s5k4h7yxsunnymipiraw_limalSensor.o
else
obj-y += s5k4h7yxsunnymipiraw_Sensor.o
endif
