
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_c/inc

obj-$(CONFIG_USB_C_SWITCH_FUSB302) += fusb302/
obj-$(CONFIG_USB_C_SWITCH_SII70XX) += sii7033/
obj-$(CONFIG_USB_C_SWITCH_ANX7418) += anx7418/
# lenovo_sw wengjun modify
obj-$(CONFIG_USB_C_SWITCH_FUSB301A) += fusb301a/
obj-$(CONFIG_USB_C_SWITCH_TUSB320L) += tusb320l/

