subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
obj-$(CONFIG_RSEE) += rsee.o
rsee-objs += core.o
rsee-objs += call.o
rsee-objs += rpc.o
rsee-objs += supp.o
rsee-objs += clk_ctrl.o
rsee-objs += debug.o
