#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifneq (, $(findstring limal, $(TARGET_PRODUCT)))
obj-y += s5k3l6_mipi_raw_limalSensor.o
else
obj-y += s5k3l6_mipi_raw_Sensor.o
endif
#obj-y += s5k3l6_otp_cal.o
