# frsm analog amp driver
snd-soc-fs181x-objs := frsm-i2ca.o
snd-soc-fs181x-objs += frsm-amp-drv.o
snd-soc-fs181x-objs += frsm-i2ca-2in1.o
obj-$(CONFIG_SND_SOC_FS181X) += snd-soc-fs181x.o

audio_spkr_amp_mngr-objs := spkr-amp-mngr.o
obj-$(CONFIG_SND_SOC_FS181X) += audio_spkr_amp_mngr.o
