#drivers/input/touchscreen/mediatek/focaltech_touch/focaltech_test
#
#Makefile for test module
#
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/$(CONFIG_TOUCHSCREEN_MTK_FTS_DIRECTORY)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/base

obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft3d47.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft6x36.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft5822.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8201.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8736.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_fte716.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8606.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft3c47.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8006u.o
obj-$(CONFIG_TOUCHSCREEN_FT8006U) += focaltech_test_ft8006m.o

