#ifndef _LINUX_OCP2138_H
#define _LINUX_OCP2138_H

typedef enum
{
	LCM_LDO_VOL_4V0 = 0,
	LCM_LDO_VOL_4V1,
	LCM_LDO_VOL_4V2,
	LCM_LDO_VOL_4V3,
	LCM_LDO_VOL_4V4,
	LCM_LDO_VOL_4V5,
	LCM_LDO_VOL_4V6,
	LCM_LDO_VOL_4V7,
	LCM_LDO_VOL_4V8,
	LCM_LDO_VOL_4V9,
	LCM_LDO_VOL_5V0,
	LCM_LDO_VOL_5V1,
	LCM_LDO_VOL_5V2,
	LCM_LDO_VOL_5V3,
	LCM_LDO_VOL_5V4,
	LCM_LDO_VOL_5V5,
	LCM_LDO_VOL_5V6,
	LCM_LDO_VOL_5V7,
	LCM_LDO_VOL_5V8,
	LCM_LDO_VOL_5V9,
	LCM_LDO_VOL_6V0,
	LCM_LDO_VOL_6V1,
	LCM_LDO_VOL_6V2,
	LCM_LDO_VOL_6V3,
	LCM_LDO_VOL_6V4,
	LCM_LDO_VOL_6V5,
         LCM_LDO_VOL_DEFAULT,
	LCM_LDO_VOL_MAX,
}LCM_LDO_VOLTAGE_E;

extern int ocp2138_BiasPower_enable(LCM_LDO_VOLTAGE_E avdd, LCM_LDO_VOLTAGE_E avee,u32 pwrup_delay);
extern int ocp2138_BiasPower_disable(u32 pwrdown_delay);
#endif /* _LINUX_OCP2138_H */

