# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/mot_vicky_s5khm6mipiraw_Sensor.o \
	$(subdrv-rpath)/mot_s5khm6_eeprom.o
#	$(subdrv-rpath)/mot_vicky_s5khm6_eeprom.o
