# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
        $(subdrv-rpath)/mot_kansas_s5kjns2ndmipiraw_Sensor.o \
	$(subdrv-rpath)/mot_s5kjns_2nd_mipi_raw_eeprom.o

