# Makefile for Linux samples code
subdir-ccflags-$(CONFIG_TINNO_PRODUCT_INFO) += -I$(srctree)/tinno/common_features/dev_info
#obj-$(CONFIG_CUSTOM_KERNEL_ALSPS) += alsps/
#obj-$(CONFIG_CUSTOM_KERNEL_ACCELEROMETER) += accelerometer/
#obj-$(CONFIG_CUSTOM_KERNEL_MAGNETOMETER)   += magnetometer/
obj-$(CONFIG_CUSTOM_KERNEL_HALL) += hall/
#obj-$(CONFIG_CUSTOM_KERNEL_GYROSCOPE) += gyroscope/

