/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
*GOODIX (C) 2013. All rights reserved.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/


#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

#if defined(CONFIG_GTP_HEADER_FW_UPDATE)
unsigned char gtp_default_FW[] = {
};
#endif

/*
*[HW INFO]00900600
*[PID]9150
*[VID]1010
*[GENERATED]2013/11/16 20:59:13
*/
#if defined(CONFIG_GTP_COMPATIBLE_MODE)
unsigned char gtp_default_FW_fl[] = {
};

unsigned char gtp_default_FW_hotknot[] = {
};

unsigned char gtp_default_FW_hotknot2[] = {
};
#endif

#endif
