ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/wake_gesture/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/
obj-y	:=  bma4.o bma455n.o bma4xy_driver.o 

