###add dtv ---lenovo@lenovo.com ---20161119 start 
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/
obj-y := bbm.o fc8180.o fc8180_bb.o fc8180_i2c.o fc8180_isr.o fc8180_ppi.o fc8180_spi.o fc8180_spib.o fc8180_tun.o fci_bypass.o fci_hal.o fci_hpi.o fci_i2c.o fci_oal.o fci_ringbuffer.o fci_tun.o
###add dtv ---lenovo@lenovo.com ---20161119 end 