#xuzhifeng@wind-mobi.com add at 20161108 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += ili9881_hd720_dsi_vdo_tm.o

#xuzhifeng@wind-mobi.com add at 20161108 end