# include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/ccci_util/$(MTK_PLATFORM)
# always build-in parts
obj-$(CONFIG_MTK_CCCI_DEVICES) += ccci_off.o
