obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += venc_vp8_if.o venc_vp8_vpu.o

ccflags-y += \
    -I$(srctree)/include/ \
    -I$(srctree)/drivers/media/platform/mediatek/ \
    -I$(srctree)/drivers/media/platform/mediatek/include \
    -I$(srctree)/drivers/media/platform/mediatek/vp8_enc \
